// @generated by tools/windows-ctrl-export/derive.py; do not edit.
// Public source: OGKM 580.65.06 307159f2623d3bf45feb9177bd2da52ffbc5ddf9 (src/common/sdk/nvidia/inc/g_finn_rm_api.h).
// Retail PE SHA256: 31c79cce80b573e21647ace8d1a2b65697f992e7f86196f89e30af477b1bd47c.
// Each control: its id from the OGKM FINN interface macro + the message number in
// tools/windows-ctrl-export/stubs.txt; paramSize and flags from its NVOC_EXPORTED_METHOD_DEF row.
pub(super) const CELLS: &[super::StubCell] = &[super::StubCell {
    wire_version: crate::DriverVersion {
        major: 580,
        minor: 65,
        patch: 6,
    },
    windows_name: "580.88",
    controls: &[super::StubControl {
        cmd: 0x2081010d,
        interface: "FINN_NV2081_BINAPI_INTERFACE_ID",
        message: 0xd,
        param_size: 0,
        export_flags: 0x10208,
        export_row_rva: 0xed23f0,
        reason: "bisect-run38-41",
    }],
}];
