// @generated by tools/windows-runlist-probe/derive.py; do not edit.
// Public source: OGKM 580.65.06 307159f2623d3bf45feb9177bd2da52ffbc5ddf9.
// Retail PE SHA256: 31c79cce80b573e21647ace8d1a2b65697f992e7f86196f89e30af477b1bd47c.
// RS_RESOURCE_DESC RVA 0x1135a40 SHA256: 762d4518ab3a38dd7777e2245315c64f67612c176fea98b87fd1b7a8d96c1ce0.
// Diagnostic class evidence only; this is NOT an OGKM-defined class identifier.
pub(super) const CELLS: &[super::EvidenceCell] = &[super::EvidenceCell {
    wire_version: crate::DriverVersion {
        major: 580,
        minor: 65,
        patch: 6,
    },
    windows_name: "580.88",
    class: 0xb297,
    size: 12,
    engine: 0,
    max_tsgs: 4,
    qos: 8,
    observed_control: 0x20801111,
    observed_control_size: 40,
    alloc_memory_size: 56,
    alloc_memory_fields: &[
        ("hClient", 0, 4),
        ("hDevice", 4, 4),
        ("hMemory", 8, 4),
        ("hClass", 12, 4),
        ("flags", 16, 4),
        ("pteAdjust", 20, 4),
        ("format", 24, 4),
        ("length", 32, 8),
        ("pageCount", 40, 4),
    ],
}];
