# SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-or-later
# kf_run_app.ps1 -Id APP -- supervise ONE app of the Windows app matrix and write its FACTS.
# The verdict (PASS/FAIL/TIMEOUT/NOTRUN) is decided on the host (verdict.py) from these facts, so the
# pass predicate is the same Python regex code for every app and is unit-tested without a guest.
#
# Files (all under C:\kf):
#   apps\ID.json       the spec the driver pushed: {id, script, timeout_s, sample_s, smi, kill_names}
#   apps\ID.ps1        the app's command script (generated by the driver from apps.json)
#   results\ID.start   START MARKER, written before the app starts ({app,start_utc,boot_utc,pid,session})
#   logs\ID.log        stdout+stderr of the app, first line `=== ID start=...`, last line `=== end rc=... secs=...`
#   results\ID.json    the facts, written LAST and atomically = the EXIT LINE of the supervisor
# A start marker without a result file after the timeout means the supervisor itself died (guest
# rebooted, bugcheck): the host books that as a crash with the boot-time change as evidence.
# The app runs as a child `powershell -File ID.ps1` of this process; the whole process tree is sampled
# (GPU Engine counters per pid, nvidia-smi) and killed (taskkill /T /F) at the timeout.
param([Parameter(Mandatory = $true)][string]$Id)
$ErrorActionPreference = 'Continue'
. "$PSScriptRoot\kf_common.ps1"
Initialize-KfDirs
$specPath = "C:\kf\apps\$Id.json"
$spec = Read-Json $specPath
$log = "C:\kf\logs\$Id.log"; $out = "$log.out"; $errf = "$log.err"
$resP = "C:\kf\results\$Id.json"; $startP = "C:\kf\results\$Id.start"
Remove-Item -Force -ErrorAction SilentlyContinue $resP, $startP, $out, $errf, $log
$timeout = 120; if ($spec.timeout_s) { $timeout = [int]$spec.timeout_s }
$sampleS = 2; if ($spec.sample_s) { $sampleS = [int]$spec.sample_s }
$smiEvery = 5; if ($spec.smi_every_s) { $smiEvery = [int]$spec.smi_every_s }
$t0 = Get-Date
$boot0 = Get-BootTimeUtc
$sess = [System.Diagnostics.Process]::GetCurrentProcess().SessionId
Write-JsonAtomic @{ app = $Id; token = $spec.token; start_utc = $t0.ToUniversalTime().ToString('o'); boot_utc = $boot0; pid = $PID; session = $sess } $startP
"=== $Id start=$($t0.ToString('o')) host=$env:COMPUTERNAME session=$sess boot=$boot0 timeout=$timeout" | Set-Content -Path $log -Encoding UTF8

$nv = Get-NvidiaLuids
$smi0 = Get-SmiSample
New-Item -ItemType Directory -Force -Path "C:\kf\out\$Id" | Out-Null
$p = Start-Process -FilePath 'powershell.exe' -ArgumentList @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $spec.script) `
    -RedirectStandardOutput $out -RedirectStandardError $errf -PassThru -WindowStyle Hidden
$null = $p.Handle   # keep the handle so ExitCode is readable after exit
$rootPid = $p.Id

$pdhNv = @{}; $pdhOther = @{}; $pdhSamples = 0; $allPids = @{}
$smiMax = 0.0; $smiMem = 0.0; $smiSamples = 0
if ($smi0) { $smiMem = $smi0.mem_mb }
$lastSize = 0; $lastGrow = Get-Date; $timedOut = $false
$nextSample = 1.0; $nextSmi = 1.0
while (-not $p.HasExited) {
    Start-Sleep -Milliseconds 500
    $el = ((Get-Date) - $t0).TotalSeconds
    $sz = 0
    foreach ($f in $out, $errf) { if (Test-Path $f) { $sz += (Get-Item $f).Length } }
    if ($sz -ne $lastSize) { $lastSize = $sz; $lastGrow = Get-Date }
    if ($el -ge $nextSample) {
        $nextSample = $el + $sampleS
        $ids = Get-ProcessTreeIds -RootPid $rootPid
        # Edge's browser process is not reliably a descendant of the supervisor (native baseline: the tree held 3 pids, none of Edge's
        # 10+), so for kf_edge apps add every msedge.exe: the video-decode / 3D engine use is in the Edge GPU process
        if ($Id -like "edge_*") { $ids = @($ids) + @(Get-Process -Name msedge -ErrorAction SilentlyContinue | ForEach-Object { [int]$_.Id }) }
        foreach ($i in $ids) { $allPids[[string]$i] = 1 }
        $s = Get-GpuEngineSample -Pids $ids -NvLuids $nv
        $pdhSamples++
        foreach ($k in $s.nv.Keys) { if (-not $pdhNv.ContainsKey($k) -or $pdhNv[$k] -lt $s.nv[$k]) { $pdhNv[$k] = $s.nv[$k] } }
        foreach ($k in $s.other.Keys) { if (-not $pdhOther.ContainsKey($k) -or $pdhOther[$k] -lt $s.other[$k]) { $pdhOther[$k] = $s.other[$k] } }
    }
    if ($spec.smi -ne $false -and $el -ge $nextSmi) {
        $nextSmi = $el + $smiEvery
        $m = Get-SmiSample
        if ($m) { $smiSamples++; if ($m.util -gt $smiMax) { $smiMax = $m.util }; if ($m.mem_mb -gt $smiMem) { $smiMem = $m.mem_mb } }
    }
    if ($el -ge $timeout) {
        $timedOut = $true
        & taskkill.exe /PID $rootPid /T /F 2>&1 | Out-Null
        if ($spec.kill_names) { foreach ($n in $spec.kill_names) { & taskkill.exe /IM $n /F 2>&1 | Out-Null } }
        break
    }
}
$t1 = Get-Date
$rc = 124
if (-not $timedOut) { try { $p.WaitForExit(); $rc = $p.ExitCode } catch { $rc = -1 } }
$quiet = [int]($t1 - $lastGrow).TotalSeconds
$secs = [int][math]::Round(($t1 - $t0).TotalSeconds)

# merge the output into the one log the host reads
$body = @()
if (Test-Path $out) { $body += Get-Content -Path $out -ErrorAction SilentlyContinue }
if ((Test-Path $errf) -and (Get-Item $errf).Length -gt 0) { $body += '[stderr]'; $body += Get-Content -Path $errf -ErrorAction SilentlyContinue }
Add-Content -Path $log -Value $body -Encoding UTF8
Add-Content -Path $log -Value ("=== end rc=$rc secs=$secs " + $t1.ToString('o')) -Encoding UTF8

# end-of-app health and accounting
$ev = Get-GuestEventSummary -Since $t0
$boot1 = Get-BootTimeUtc
# [string] casts: Get-Content strings carry PSPath/PSDrive note properties that Windows PowerShell 5.1's ConvertTo-Json expands (to -Depth 8: minutes of CPU)
$tail = @(Get-Content -Path $log -Tail 40 -ErrorAction SilentlyContinue | ForEach-Object { [string]$_ })
$digests = @(Get-Content -Path $log -ErrorAction SilentlyContinue | Where-Object { $_ -match '^(OUTSHA|DIGEST) ' } | Select-Object -First 8 | ForEach-Object { [string]$_ })
$files = @(Get-ChildItem -Path "C:\kf\out\$Id" -Recurse -File -ErrorAction SilentlyContinue | Select-Object -First 20 | ForEach-Object { '{0} {1}' -f $_.FullName, $_.Length })
$gpuErr = @(Get-CimInstance Win32_VideoController -ErrorAction SilentlyContinue | Where-Object { $_.Name -match 'NVIDIA' } | ForEach-Object { '{0} status={1} code={2}' -f $_.Name, $_.Status, $_.ConfigManagerErrorCode })
$facts = @{
    app = $Id; token = $spec.token; rc = $rc; secs = $secs; quiet = $quiet; timed_out = $timedOut
    start_utc = $t0.ToUniversalTime().ToString('o'); end_utc = $t1.ToUniversalTime().ToString('o')
    boot_utc_start = $boot0; boot_utc_end = $boot1; session = $sess
    pdh = @{ nv = $pdhNv; other = $pdhOther; samples = $pdhSamples; pids = @($allPids.Keys); nvidia_luids = $nv }
    smi = @{ util_max = $smiMax; mem_used_max_mb = $smiMem; mem_used_base_mb = $(if ($smi0) { $smi0.mem_mb } else { $null }); samples = $smiSamples }
    events = $ev; gpu_devices = $gpuErr
    log_tail = $tail; digests = $digests; out_files = $files
}
Write-JsonAtomic $facts $resP 8
exit 0
