[workspace]
resolver = "2"
members = [
    "crates/kayfabe-util",
    "crates/kayfabe-arch",
    "crates/kayfabe-abi",
    "crates/kayfabe-mmu",
    "crates/kayfabe-vmm",
    "crates/kayfabe-vmm-kvm",
    "crates/kayfabe-isolate",
    "crates/kayfabe-completion",
    "crates/kayfabe-core",
    "crates/kayfabe-fwd",
    "crates/kayfabe-gsp",
    "crates/kayfabe-trace",
    "crates/kayfabe-mocks",
    "crates/kayfabe-rt",
    "crates/kayfabe-linux-raw",
    "tests",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Proprietary"
authors = ["kayfabe"]

[workspace.dependencies]
kayfabe-util = { path = "crates/kayfabe-util" }
kayfabe-arch = { path = "crates/kayfabe-arch" }
kayfabe-abi = { path = "crates/kayfabe-abi" }
kayfabe-mmu = { path = "crates/kayfabe-mmu" }
kayfabe-vmm = { path = "crates/kayfabe-vmm" }
kayfabe-vmm-kvm = { path = "crates/kayfabe-vmm-kvm" }
kayfabe-isolate = { path = "crates/kayfabe-isolate" }
kayfabe-completion = { path = "crates/kayfabe-completion" }
kayfabe-core = { path = "crates/kayfabe-core" }
kayfabe-fwd = { path = "crates/kayfabe-fwd" }
kayfabe-gsp = { path = "crates/kayfabe-gsp" }
kayfabe-trace = { path = "crates/kayfabe-trace" }
kayfabe-mocks = { path = "crates/kayfabe-mocks" }
kayfabe-rt = { path = "crates/kayfabe-rt" }
kayfabe-linux-raw = { path = "crates/kayfabe-linux-raw" }

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"
