#!/usr/bin/env python3
"""Render only explicitly source-audited compressed-contiguous contract cells.
Input is the companion public-source compiler emitter's evidence, not a trace.
See README.md for behavioral proof independent of identical wire layouts.
"""
import hashlib
import json
import subprocess
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
TAGS = {'565.57.01', '570.86.15', '580.65.06', '580.126.09', '580.159.04', '580.173.02', '595.91.07', '610.43.02', '615.71.09'}
manifest = json.loads((ROOT/'tools/windows-debug-capture/evidence/alloc-memory-20261005/compiler-layouts.json').read_text())
assert manifest['probe_sha256'] == hashlib.sha256((ROOT/'tools/windows-debug-capture/alloc-memory-layout.c').read_bytes()).hexdigest()
rows = [r for r in manifest['rows'] if r['tag'] in TAGS]
assert len(rows) == len(TAGS) and {r['tag'] for r in rows} == TAGS
assert all(r['status'] == 'MEASURED' and not r['compiler_diagnostics'] for r in rows)
out = ['// Generated by tools/memory-list-probe/generate.py; do not edit.', 'use super::{Cell, Field};', 'pub(super) const CELLS: &[Cell] = &[']
for row in rows:
    f = row['facts']; c=f['constants']; r=f['rpc_alloc_memory']; p=f['pte_desc']; flags=f['flags']
    assert c['NV_VGPU_PTE_64_SIZE'] == 8 and r['size'] == r['pteDesc'] + p['pte_pde']
    def field(name):
        v=flags[name]; return f"Field {{ mask: {v['mask']}, shift: {v['shift']} }}"
    def enum(name): return c['NVOS02_FLAGS_'+name]
    version=', '.join(f'{k}: {int(v)}' for k,v in zip(['major','minor','patch'],row['tag'].split('.')))
    mask=0
    for name in ['PHYSICALITY','LOCATION','COHERENCY','REGISTER_MEMDESC_TO_PHYS_RM','MAPPING']: mask |= flags[name]['mask']
    out += [f'// {row["tag"]}: public source commit {row["commit"]}', 'Cell {', f'version: crate::DriverVersion {{ {version} }},', f'function: {c["NV_VGPU_MSG_FUNCTION_ALLOC_MEMORY"]}, class: {c["NV01_MEMORY_LIST_SYSTEM"]},',
            f'fb_class: '+(f'Some({c["NV01_MEMORY_LIST_FBMEM"]})' if row['tag'] in {'580.65.06', '580.159.04'} else 'None')+',',
            f'fb_location: {enum("LOCATION_VIDMEM")}, gpu_cache_mask: {flags["GPU_CACHEABLE"]["mask"]},',
            f'size: {r["size"]+c["NV_VGPU_PTE_64_SIZE"]},',
            'offsets: ['+', '.join(str(r[x]) for x in ['hClient','hDevice','hMemory','hClass','flags','pteAdjust','format','length','pageCount','pteDesc'])+'],',
            f'pte: {r["pteDesc"]+p["pte_pde"]}, idr_mask: {p["idr"]}, reserved_mask: {p["reserved1"]}, count_mask: {p["length"]}, idr_none: {c["NV_VGPU_PTEDESC_IDR_NONE"]},',
            f'pitch: {c["NV_MMU_PTE_KIND_PITCH"]}, page_shift: {c["RM_PAGE_SHIFT"]}, page_size: {c["RM_PAGE_SIZE"]}, allowed_flags: {mask},',
            f'physicality: {field("PHYSICALITY")}, contiguous: {enum("PHYSICALITY_CONTIGUOUS")}, location: {field("LOCATION")}, pci: {enum("LOCATION_PCI")},',
            f'cache: {field("COHERENCY")}, caches: ['+', '.join(str(enum('COHERENCY_'+s)) for s in ['UNCACHED','CACHED','WRITE_COMBINE','WRITE_THROUGH','WRITE_PROTECT','WRITE_BACK'])+'],',
            f'mapping: {field("MAPPING")}, mappings: ['+', '.join(str(enum('MAPPING_'+s)) for s in ['DEFAULT','NO_MAP','NEVER_MAP'])+'],', '},']
out += ['];']
target=ROOT/'crates/kf-abi/src/memory_list_generated.rs'
target.write_text('\n'.join(out)+'\n')
subprocess.run(['rustfmt','--edition','2024',str(target)],check=True)
