#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-or-later
# Regenerate cuda/display/kf_color.ptx from kf_color.cu with clang's NVPTX back-end — no CUDA
# SDK, no nvcc (docs/design/V3_DISPLAY.md sec. 8.11). The PTX is committed; its header records
# the clang version and the FNV-1a 64 of the source it was made from, which kf-cuda's test
# `the_pack_ptx_was_made_from_the_committed_source` recomputes, so a .cu edited without
# re-running this script turns the build red.
set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
src="$here/kf_color.cu"
out="$here/kf_color.ptx"
clang --version >/dev/null
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
clang -x cuda --cuda-device-only -nocudainc -nocudalib --cuda-gpu-arch=sm_75 -O3 -ffp-contract=off -S \
    -o "$tmp" "$src"
fnv=$(python3 -c '
import sys
h = 0xcbf29ce484222325
for b in open(sys.argv[1], "rb").read():
    h ^= b
    h = (h * 0x100000001b3) & 0xffffffffffffffff
print(f"{h:016x}")' "$src")
ver=$(clang --version | head -1 | tr -cd '[:print:]')
{
    echo "//"
    echo "// kf_color.ptx - GENERATED by cuda/display/make_color_ptx.sh from kf_color.cu; do not edit."
    echo "// compiler: $ver (NVPTX, sm_75, -O3, no CUDA SDK)"
    echo "// source fnv1a64: $fnv"
    echo "//"
    grep -v '^// Generated by LLVM NVPTX Back-End' "$tmp"
} > "$out"
LC_ALL=C grep -qP '[^\x00-\x7f]' "$out" && { echo "non-ASCII PTX (the CUDA JIT refuses it)"; exit 1; }
echo "wrote $out (source fnv1a64 $fnv)"
