#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-or-later
"""Generate kf_abi's host-owned stub cells from public OGKM and the pinned retail Windows driver.

Input: `stubs.txt` (next to this file), one line per stubbed control:
    <FINN interface macro from OGKM>  <message number>  <reason tag>
The interface VALUE is read from the public OGKM 580.65.06 checkout (`g_finn_rm_api.h`); the
control id is `(interface << 8) | message`. The id must then appear EXACTLY ONCE as the `methodId`
of a well-formed `NVOC_EXPORTED_METHOD_DEF` row (OGKM 580.65.06
`src/nvidia/inc/libraries/nvoc/runtime.h:73-84`, x86-64 without debug strings: pFunc u64, flags
u32, accessRight u32, methodId u32, paramSize u32, pClassInfo u64 = 32 bytes) in the pinned retail
`nvlddmkm.sys`; its `paramSize` and `flags` are emitted. Nothing is executed; unknown files fail.

usage: derive.py --ogkm OGKM_580.65.06 --driver nvlddmkm.sys --out crates/kf-abi/src/hoststub_generated.rs
"""
import argparse
import hashlib
from pathlib import Path
import re
import struct
import subprocess

SHA = "31c79cce80b573e21647ace8d1a2b65697f992e7f86196f89e30af477b1bd47c"
TAG_COMMIT = "307159f2623d3bf45feb9177bd2da52ffbc5ddf9"
FINN = "src/common/sdk/nvidia/inc/g_finn_rm_api.h"
ROW = struct.Struct("<QIIIIQ")


def sections(data):
    pe = struct.unpack_from("<I", data, 0x3C)[0]
    if data[pe:pe + 4] != b"PE\0\0":
        raise SystemExit("not PE")
    count, optional = struct.unpack_from("<H", data, pe + 6)[0], struct.unpack_from("<H", data, pe + 20)[0]
    base = struct.unpack_from("<Q", data, pe + 24 + 24)[0]
    table = pe + 24 + optional
    out = []
    for i in range(count):
        at = table + 40 * i
        name = data[at:at + 8].rstrip(b"\0").decode("ascii", "replace")
        vsize, va, rawsize, rawoff = struct.unpack_from("<IIII", data, at + 8)
        out.append((name, va, max(vsize, rawsize), rawoff, rawsize))
    return base, out


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--ogkm", type=Path, required=True)
    p.add_argument("--driver", type=Path, required=True)
    p.add_argument("--out", type=Path, required=True)
    a = p.parse_args()
    commit = subprocess.check_output(["git", "-C", str(a.ogkm), "rev-parse", "HEAD"], text=True).strip()
    if commit != TAG_COMMIT:
        raise SystemExit("requires the exact public OGKM 580.65.06 checkout")
    finn = (a.ogkm / FINN).read_text()
    data = a.driver.read_bytes()
    if hashlib.sha256(data).hexdigest() != SHA:
        raise SystemExit("retail driver digest is not an evidenced cell")
    base, secs = sections(data)
    end = base + max(va + size for _, va, size, _, _ in secs)

    def in_image(v):
        return base <= v < end

    rows = []
    for line in (Path(__file__).with_name("stubs.txt")).read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        macro, message, reason = line.split()
        m = re.search(rf"^#define {re.escape(macro)} \((0x[0-9A-Fa-f]+)U?\)", finn, re.M)
        if not m:
            raise SystemExit(f"{macro}: not defined in OGKM {FINN}")
        iface, msg = int(m.group(1), 16), int(message, 0)
        if not 0 <= msg <= 0xFF or iface >> 24:
            raise SystemExit(f"{macro} {message}: not a control id")
        cmd = (iface << 8) | msg
        found = []
        for name, va, _, rawoff, rawsize in secs:
            blob = data[rawoff:rawoff + rawsize]
            needle = struct.pack("<I", cmd)
            i = blob.find(needle)
            while i >= 0:
                r = i - 16
                if r >= 0 and r % 8 == 0 and r + ROW.size <= len(blob):
                    func, flags, access, mid, size, cls = ROW.unpack_from(blob, r)
                    if mid == cmd and access == 0 and size < 0x10000 and in_image(func) and in_image(cls):
                        found.append((va + r, flags, size, name))
                i = blob.find(needle, i + 1)
        if len(found) != 1:
            raise SystemExit(f"{cmd:#010x}: {len(found)} export rows, need exactly one")
        rva, flags, size, sec = found[0]
        rows.append((cmd, macro, msg, size, flags, rva, sec, reason))
    a.out.write_text(emit(rows))




def emit(rows):
    out = [
        "// @generated by tools/windows-ctrl-export/derive.py; do not edit.",
        f"// Public source: OGKM 580.65.06 {TAG_COMMIT} ({FINN}).",
        f"// Retail PE SHA256: {SHA}.",
        "// Each control: its id from the OGKM FINN interface macro + the message number in",
        "// tools/windows-ctrl-export/stubs.txt; paramSize and flags from its NVOC_EXPORTED_METHOD_DEF row.",
        "pub(super) const CELLS: &[super::StubCell] = &[super::StubCell {",
        "    wire_version: crate::DriverVersion {",
        "        major: 580,",
        "        minor: 65,",
        "        patch: 6,",
        "    },",
        '    windows_name: "580.88",',
        "    controls: &[",
    ]
    for cmd, macro, msg, size, flags, rva, sec, reason in rows:
        out += [
            "        super::StubControl {",
            f"            cmd: {cmd:#x},",
            f'            interface: "{macro}",',
            f"            message: {msg:#x},",
            f"            param_size: {size},",
            f"            export_flags: {flags:#x},",
            f"            export_row_rva: {rva:#x},",
            f'            reason: "{reason}",',
            "        },",
        ]
    out += ["    ],", "}];", ""]
    return "\n".join(out)


if __name__ == "__main__":
    main()
