#!/usr/bin/env python3
"""Census `mode2_initctrl_ga106.h` — the C artifact's captured GA106 control table.

★★★ Why this exists as a committed artifact rather than a number in a comment.

`kayfabe_abi::oracle` refuses a captured row whose body is not complete. The size of that
refusal — *which* rows, and how short each one is — is a fact about a file in a **different
repository** (`/workspace/nvidia-gpu-passthrough`, read-only, and absent in CI). A constant
transcribed from it by hand is exactly the shape this project has been bitten by: a
transcription cannot detect a shared misreading, and a `[measured]` marker that names no
run is not a measurement.

So the census is generated here, committed to `traces/c_oracle_census/`, and pinned by
`crates/kayfabe-abi/tests/initctrl_census.rs`. The test reads the committed TSV; this
script regenerates it when the C repo is on the box. If the two disagree, one of them
changed and a human has to say which.

⊘ This script says nothing about whether a captured body is *correct*. It reports how many
bytes the recorder kept, and one derived number — `trailing_zeros_kept` — that exists to
kill the "`dlen` is trailing-zero-trimmed" reading. See the module docs of
`kayfabe_abi::oracle`.

Usage:
    scripts/census_initctrl.py [--check] [--c-repo PATH]
"""

from __future__ import annotations

import argparse
import hashlib
import re
import subprocess
import sys
from pathlib import Path

DEFAULT_C_REPO = Path("/workspace/nvidia-gpu-passthrough")
HEADER = Path("src/qemu/mode2_initctrl_ga106.h")
OUT = Path("traces/c_oracle_census/initctrl_ga106_census.tsv")

ROW_RE = re.compile(
    r"\{\s*(0x[0-9a-fA-F]+)u?\s*,\s*(0x[0-9a-fA-F]+)u?\s*,"
    r"\s*(\d+)u?\s*,\s*(\d+)u?\s*,\s*(\w+)\s*\}"
)
ARR_RE = re.compile(
    r"static const unsigned char (ctl_\w+)\[\]\s*=\s*\{(.*?)\};", re.S
)
BYTE_RE = re.compile(r"0x([0-9a-fA-F]{2})")


def c_repo_rev(repo: Path) -> str:
    try:
        return subprocess.run(
            ["git", "-C", str(repo), "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
    except Exception:
        return "unknown"


def census(repo: Path) -> str:
    path = repo / HEADER
    src = path.read_text(errors="replace")

    arrays: dict[str, bytes] = {}
    for m in ARR_RE.finditer(src):
        arrays[m.group(1)] = bytes(int(b, 16) for b in BYTE_RE.findall(m.group(2)))

    lines: list[str] = []
    counts = {"complete": 0, "truncated": 0, "empty": 0}
    for lineno, line in enumerate(src.split("\n"), start=1):
        m = ROW_RE.search(line)
        if not m:
            continue
        cmd, status, psize, dlen, arr = m.group(1), m.group(2), int(m.group(3)), int(m.group(4)), m.group(5)
        body = arrays.get(arr, b"")
        # ⚠ The array's real length, not the row's claim about it. A row whose `dlen`
        # disagrees with its own array is a defect this census must be able to show.
        arrlen = len(body)
        tz = 0
        for byte in reversed(body):
            if byte:
                break
            tz += 1
        if dlen == 0:
            cls = "empty"
        elif dlen < psize:
            cls = "truncated"
        else:
            cls = "complete"
        counts[cls] += 1
        digest = hashlib.sha256(body).hexdigest()[:16]
        lines.append(
            f"0x{int(cmd, 16):08x}\t{int(status, 16)}\t{psize}\t{dlen}\t{arrlen}\t"
            f"{tz}\t{lineno}\t{cls}\t{digest}"
        )

    total = sum(counts.values())
    head = [
        "# census of mode2_initctrl_ga106.h — generated by scripts/census_initctrl.py",
        f"# c_repo_rev\t{c_repo_rev(repo)}",
        f"# total\t{total}",
        f"# complete\t{counts['complete']}",
        f"# truncated\t{counts['truncated']}",
        f"# empty\t{counts['empty']}",
        "# cmd\tstatus\tpsize\tdlen\tarrlen\ttrailing_zeros_kept\tc_line\tclass\tbody_sha256_16",
    ]
    return "\n".join(head + sorted(lines)) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if the committed TSV is stale")
    ap.add_argument("--c-repo", type=Path, default=DEFAULT_C_REPO)
    args = ap.parse_args()

    root = Path(__file__).resolve().parent.parent
    out = root / OUT

    if not (args.c_repo / HEADER).exists():
        # ⊘ Not an error: the C artifact is a separate read-only repo and is absent in CI.
        # The committed TSV is the artifact; this script is only how it was produced.
        print(f"census_initctrl: {args.c_repo / HEADER} absent — nothing to regenerate", file=sys.stderr)
        return 0

    text = census(args.c_repo)
    if args.check:
        have = out.read_text() if out.exists() else ""
        # ⚠ Compare everything except the provenance line, which moves with the C repo's
        # HEAD without the table itself changing.
        def body(s: str) -> str:
            return "\n".join(l for l in s.split("\n") if not l.startswith("# c_repo_rev"))
        if body(have) != body(text):
            print(f"census_initctrl: {OUT} is STALE — rerun without --check", file=sys.stderr)
            return 1
        print(f"census_initctrl: {OUT} matches the C header")
        return 0

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)
    print(f"census_initctrl: wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
