RFRES side=host w=cup2 rc=0 secs=3 recs=404 verdict=PASS
RFRES side=host w=cup3 rc=0 secs=2 recs=403 verdict=PASS
RFRES side=host w=cup8 rc=0 secs=3 recs=409 verdict=PASS
RFRES side=host w=blocksync rc=0 secs=9 recs=416 verdict=PASS
RFRES side=host w=torch_correct rc=0 secs=9 recs=840 verdict=PASS
RFRES side=host w=torch_train rc=0 secs=10 recs=799 verdict=PASS
RFRES side=host w=llama_gen rc=0 secs=3 recs=749 verdict=PASS
RFRES side=host w=clpeak rc=0 secs=130 recs=640 verdict=PASS
RFRES side=host w=vulkaninfo rc=0 secs=2 recs=1428 verdict=PASS
RFRES side=host w=vkpeak rc=0 secs=362 recs=10778 verdict=PASS
RFRES side=host w=egl_offscreen rc=0 secs=15 recs=672 verdict=PASS
RFRES side=host w=nvenc_h264 rc=0 secs=5 recs=1672 verdict=PASS
RFRES side=host w=nvenc_hevc rc=0 secs=5 recs=1547 verdict=PASS
RFRES side=host w=nvdec_h264 rc=0 secs=6 recs=1285 verdict=PASS
RFRES side=host w=nvidia_smi rc=0 secs=11 recs=501 verdict=PASS
RFRES side=host w=gpu_burn rc=0 secs=48 recs=625 verdict=PASS
RFRES side=host w=simpleStreams rc=0 secs=4 recs=451 verdict=PASS
RFRES side=host w=simpleCudaGraphs rc=0 secs=3 recs=465 verdict=PASS
RFRES side=host w=graphMemoryNodes rc=0 secs=5 recs=469 verdict=PASS
RFRES side=host w=simpleIPC rc=0 secs=3 recs=865 verdict=PASS
RFRES side=host w=asyncAPI rc=0 secs=2 recs=438 verdict=PASS
RFRES side=host w=simpleCallback rc=0 secs=3 recs=459 verdict=PASS
