//! ★ The display plane's own GPU context — how the emulated display engine reaches the guest's
//! framebuffer (the store) WITHOUT the CPU (`THE_CONSTRAINTS.md` §38: *"the CPU never reads guest
//! vidmem"*; `docs/design/V3_DISPLAY.md` §4.3–§4.6).
//!
//! The display engine is an emulated device, and the store is its memory: the context-DMA table in
//! the guest's display instance memory (FB) is read here, a video-memory notifier or semaphore is
//! written here, and (M2) a flipped surface is copied out of the store here by the GPU. Every access
//! is bounds-checked against the imported store before a byte moves; the device pointer never leaves
//! this struct (§13).
//!
//! ⊘ A SEPARATE context from the walker's (`walk.rs`): the walker is owned by the VA thread and its
//! synchronous accesses order behind walks; the display worker must never wait on a walk, and a
//! walk must never wait on a scanout copy.

use crate::driver_unsafe::{
    CUdeviceptr, CompletionFd, CtxHandle, Cuda, CudaError, EventHandle, Func, PinnedBuf,
    StreamHandle,
};

/// ★ The display plane's kernels, hand-written PTX (`cuda/display/kf_scanout.ptx`), JIT-compiled at
/// the plane's bring-up; the block-linear address function is `kf_disp::scanout::bl_offset`.
pub static SCANOUT_PTX: &[u8] = include_bytes!("../../../cuda/display/kf_scanout.ptx");

/// The compose kernel's entry point: one window into the head's staging frame.
pub const COMPOSE_ENTRY: &str = "kf_compose";

/// ★ The GPU-copy broker rung's pack kernel (`cuda/display/kf_bl_pack.ptx`, generated by
/// `cuda/display/make_pack_ptx.sh` from `kf_bl_pack.cu` with clang's NVPTX back-end — the same
/// source kf-disp's `tests/bl_pack_kernel.rs` runs on the host against
/// `kf_disp::vramslot::pack_reference`). `docs/design/V3_DISPLAY.md` §8.11.
pub static PACK_PTX: &[u8] = include_bytes!("../../../cuda/display/kf_bl_pack.ptx");

/// The pack kernel's entry point.
pub const PACK_ENTRY: &str = "kf_bl_pack";
/// Threads per pack CTA (eight GOBs; `KF_PACK_THREADS` in the source).
pub const PACK_THREADS: u32 = 256;

/// ★ `display-max-fps`'s change detector (`cuda/display/kf_sum.ptx`, hand-written, its own module so
/// a JIT refusal costs only the detection): per row of the staging frame, the sum of a mixed term
/// per pixel (`kf_disp::pace::row_sums` is the CPU reference, and kf-disp's
/// `tests/compose_kernel.rs` runs this PTX against it). `docs/design/V3_DISPLAY.md` §8.16.
pub static SUM_PTX: &[u8] = include_bytes!("../../../cuda/display/kf_sum.ptx");
/// The checksum kernel's entry point.
pub const SUM_ENTRY: &str = "kf_sum";
/// Threads per checksum CTA (one CTA per row).
pub const SUM_THREADS: u32 = 256;

/// Real SDR colour kernels, generated from the committed CUDA source.
pub static COLOR_PTX: &[u8] = include_bytes!("../../../cuda/display/kf_color.ptx");

/// ★ The console copy's semi-planar YUV window kernel (`cuda/display/kf_yuv.cu`, generated by
/// `make_yuv_ptx.sh` with clang's NVPTX back-end). Its own module: a failure to load costs only the
/// YUV windows of the console copy (they are left out, by name), never the RGB composition.
pub static YUV_PTX: &[u8] = include_bytes!("../../../cuda/display/kf_yuv.ptx");

/// The YUV kernel's entry (XRGB8888 staging frame) …
pub const YUV_ENTRY: &str = "kf_compose_yuv";
/// … and its twin for the SDR colour pipeline's FP32 frame.
pub const YUV_COLOR_ENTRY: &str = "kf_color_yuv";
const COLOR_LUT_BYTES: usize = (4 + 1025) * 8;

/// A bounded source span; the table is copied device-to-device before it is used.
#[derive(Debug, Clone, Copy)]
pub struct ColorLut {
    /// Authored sample count including endpoint, bounded by the fixed allocation.
    pub entries: u32,
    /// Byte offset into the imported store, bounded again at the GPU binding.
    pub src: u64,
    /// Interpolate between entries instead of selecting the lower entry.
    pub interpolate: bool,
    /// Worker-authored identity of the armed binding. A new UPDATE/free/reallocation
    /// changes it even if the guest reuses the same store address.
    pub token: u64,
}

/// Bounded register-authored CSC program uploaded to a fixed per-window allocation.
/// This is program data, not a CPU read or transform of guest pixels/LUT memory.
#[derive(Debug, Clone)]
pub struct ColorPipeline {
    /// CSC00, CSC01, CSC10, CSC11 encoded signed coefficients.
    pub matrices: [[i32; 12]; 4],
    /// Two fixed segment arrays: 33 logarithmic / 64 linear segments.
    pub segments: [[u32; 64]; 2],
    /// Two fixed entry arrays, with their interpolation endpoint.
    pub entries: [[u32; 1025]; 2],
    /// Enabled inline table stages.
    pub enable: [bool; 2],
}
const COLOR_PIPELINE_BYTES: usize = (4 * 12 + 2 * 64 + 2 * 1025 + 2) * 4;

impl ColorPipeline {
    fn bytes(&self) -> Result<Vec<u8>, String> {
        for stage in 0..2 {
            if !self.enable[stage] {
                continue;
            }
            let count = if stage == 0 { 33 } else { 64 };
            let mut entries = 0_usize;
            for &log in &self.segments[stage][..count] {
                if log > 7 {
                    return Err("CSC segment outside fixed bound".into());
                }
                entries += 1_usize << log;
            }
            if entries > 1024
                || self.entries[stage][..=entries]
                    .iter()
                    .any(|&v| v > 65535 || (stage == 1 && v >= 0x7c00))
            {
                return Err("CSC table exceeds fixed extent or format".into());
            }
        }
        let mut bytes = Vec::with_capacity(COLOR_PIPELINE_BYTES);
        for matrix in &self.matrices {
            for v in matrix {
                bytes.extend_from_slice(&v.to_le_bytes());
            }
        }
        for table in &self.segments {
            for v in table {
                bytes.extend_from_slice(&v.to_le_bytes());
            }
        }
        for table in &self.entries {
            for v in table {
                bytes.extend_from_slice(&v.to_le_bytes());
            }
        }
        for enabled in self.enable {
            bytes.extend_from_slice(&u32::from(enabled).to_le_bytes());
        }
        Ok(bytes)
    }
}

/// Synthetic tone fixture; uploaded only to a private scratch store for the oracle.
#[derive(Clone, Copy)]
pub struct ColorTone<'a> {
    /// Fixed UNORM16 intensity table, including VSS header and endpoint.
    pub table: &'a [u8],
    /// Register-authored CSC program.
    pub pipeline: &'a ColorPipeline,
    /// Change the source after its first snapshot to test immutable retention.
    pub mutate: Option<&'a [u8]>,
    /// Rearm after mutation instead of retaining the first snapshot.
    pub rearm: bool,
}

/// Synthetic SDR fixture for the hardware oracle; all bytes are host-authored.
pub struct ColorFixture<'a> {
    /// RGB8888 pixels.
    pub surface: &'a [u8],
    /// DIRECT8/DIRECT10 FP16 input table with its header and endpoint.
    pub input: &'a [u8],
    /// DIRECT8/DIRECT10 fixed-point output table with its header and endpoint.
    pub output: &'a [u8],
    /// Source rectangle and blend parameters.
    pub layer: &'a ComposeLayer,
    /// Encoded output CSC coefficients.
    pub matrix: &'a [i32; 12],
    /// Output dimensions.
    pub size: (u32, u32),
    /// Exercise fractional output indices.
    pub interpolate: bool,
    /// Mutate the synthetic input source after its snapshot was consumed, then
    /// compose again to check retention. Never modifies guest memory.
    pub mutate_input: Option<&'a [u8]>,
    /// After mutation, explicitly rearm the input to require a fresh snapshot.
    pub rearm: bool,
    /// Optional pre-composition tone stage.
    pub tone: Option<ColorTone<'a>>,
}

/// ★ An imported display slot — a VRAM frame object kayfabe allocated itself (never guest
/// memory), named by its index here; its device pointer and length never leave [`DisplayGpu`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SlotId(usize);

/// ★ One pack: a `width`×`height` staging frame into a slot's block-linear extent. The values
/// come from `kf_disp::vramslot::slot_geom` and its `GobLayout`; [`BlPack::check`] re-derives
/// every one of them here before a launch, so a drift between the two crates is a refusal, never
/// an out-of-bounds write.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BlPack {
    /// Pixels per row.
    pub width: u32,
    /// Rows.
    pub height: u32,
    /// GOBs per row.
    pub gobs_per_row: u32,
    /// log2 GOBs per block.
    pub h_log2: u32,
    /// GOBs the extent holds.
    pub gobs: u64,
    /// The in-GOB bits of `y0, y1, x4, y2, x5`.
    pub bits: [u32; 5],
}

impl BlPack {
    /// ⊘ The launch's bounds: the geometry is the one `(width, height, h_log2)` implies, the
    /// layout is a permutation of bits 4..=8, the extent fits `slot_bytes`, and the staging frame
    /// holds `4·w·h` bytes.
    ///
    /// # Errors
    /// The bound that failed, by name.
    pub fn check(&self, slot_bytes: u64, staging_bytes: u64) -> Result<(), String> {
        let p = *self;
        if p.width == 0 || p.height == 0 || p.width > 16384 || p.height > 16384 || p.h_log2 > 5 {
            return Err(format!("{p:?} is not a packable frame"));
        }
        let gpr = (p.width * 4).div_ceil(64);
        let gobs = (u64::from(p.height.div_ceil(8 << p.h_log2)) * u64::from(gpr)) << p.h_log2;
        if p.gobs_per_row != gpr || p.gobs != gobs {
            return Err(format!(
                "{p:?}: a {}x{} frame at 2^{} GOBs a block is {gpr} GOBs a row and {gobs} GOBs",
                p.width, p.height, p.h_log2
            ));
        }
        let mut seen = 0u32;
        for b in p.bits {
            if !(4..=8).contains(&b) || seen & (1 << b) != 0 {
                return Err(format!(
                    "{p:?}: the GOB bits are not a permutation of 4..=8"
                ));
            }
            seen |= 1 << b;
        }
        if gobs * 512 > slot_bytes {
            return Err(format!(
                "{p:?}: {:#x} bytes do not fit the {slot_bytes:#x}-byte slot",
                gobs * 512
            ));
        }
        if u64::from(p.width) * u64::from(p.height) * 4 > staging_bytes {
            return Err(format!(
                "{p:?}: the staging frame holds {staging_bytes:#x} bytes"
            ));
        }
        Ok(())
    }
}

/// ★ The display worker's GPU context with the store imported.
pub struct DisplayGpu {
    cu: Cuda,
    ctx: CtxHandle,
    device: i32,
    store: Option<(CUdeviceptr, u64)>,
    /// The scanout copies' stream (blocking, like every stream this binding creates).
    stream: StreamHandle,
    /// Readable once the last queued scanout copy completed (`cuLaunchHostFunc` after it).
    done: CompletionFd,
    /// The compose kernel, or why it did not load (every scanout is refused by it).
    compose: Result<Func, String>,
    /// The device staging frame the windows compose into: address and bytes.
    staging: Option<(CUdeviceptr, usize)>,
    /// The pack kernel, or why it did not load (the GPU-copy rung is refused by it).
    pack: Result<Func, String>,
    /// ★ The imported display slots: device pointer and bytes, indexed by [`SlotId`]. Never
    /// unmapped while the device lives (a compositor may hold an import of any of them).
    slots: Vec<(CUdeviceptr, u64)>,
    /// ★ `display-max-fps`: the checksum kernel, or why it did not load (every non-flip check is
    /// then sent — the detection is lost, never the picture).
    sum: Result<Func, String>,
    /// Its row sums: the device buffer (zeroed before each launch), the page-locked copy the worker
    /// reads after the completion, and the rows both hold. Grown, never shrunk.
    sums: Option<(CUdeviceptr, PinnedBuf, usize)>,
    color: Result<[Func; 4], String>,
    /// ★ The YUV window kernel, or why it did not load.
    yuv: Result<[Func; 2], String>,
    color_frame: Option<(CUdeviceptr, usize)>,
    /// Fixed slots: 32 ILUTs, 32 TMO tables and one OLUT. Never guest-sized.
    color_luts: Option<CUdeviceptr>,
    color_pipelines: Option<CUdeviceptr>,
    color_status: Option<(CUdeviceptr, PinnedBuf)>,
    color_event: EventHandle,
    color_recorded: bool,
    color_snapshots: [Option<ColorLut>; 65],
    /// ★ 2026-10-08 (`V3_DISPLAY.md` §8.18): recorded with every completion signal, so a copy whose
    /// signal is late can be asked "still queued, or failed?" without blocking.
    signal_event: EventHandle,
}

/// ★ One page-locked host frame buffer the display console reads (M2). Its address crosses to the
/// QEMU console as an integer; this crate writes it only through the GPU copy engine.
///
/// Two backings: `cuMemAllocHost` ([`DisplayGpu::frame`], the console alone), or — with the
/// display broker on — a mapping of a sealed memfd the broker also receives, page-locked with
/// `cuMemHostRegister` ([`DisplayGpu::frame_over`]). The frame then OWNS that mapping, so the
/// registration can never outlive the pages it pins.
pub struct Frame {
    buf: PinnedBuf,
    map: Option<kf_linux_raw::MappedRegion>,
}

impl Frame {
    /// Host address of the frame's first byte.
    #[must_use]
    pub fn addr(&self) -> usize {
        self.buf.addr()
    }

    /// Bytes.
    #[must_use]
    pub fn len(&self) -> usize {
        self.buf.len()
    }

    /// Never empty (a zero-length frame is refused at allocation).
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.buf.len() == 0
    }

    /// A copy of `n` bytes at `off` — for a diagnostic digest of a frame whose copy COMPLETED
    /// (the console reads the same bytes to show them). ⊘ Never while a copy targets the frame.
    ///
    /// # Panics
    /// If the range leaves the frame.
    #[must_use]
    pub fn read(&self, off: usize, n: usize) -> Vec<u8> {
        self.buf.read(off, n)
    }
}

impl Drop for Frame {
    fn drop(&mut self) {
        // ⊘ A registered frame dropped WITHOUT `DisplayGpu::release_frame` keeps its pages
        // mapped: the registration must never outlive the mapping it pins.
        if let Some(m) = self.map.take() {
            std::mem::forget(m);
        }
    }
}

impl std::fmt::Debug for Frame {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Frame").field("len", &self.len()).finish()
    }
}

/// Every [`ComposeLayer::flags`] bit `kf_compose` knows: alpha, swap red/blue, opaque, and (§O,
/// 2026-10-04) XOR — `out = below XOR (source & 0x00ffffff)`. A layer with another bit is refused
/// before a launch: the kernel would silently treat it as a blend.
pub const COMPOSE_FLAGS: u32 = 0xf;

/// ★ One window's compose-kernel program (the mirror of `kf_disp::scanout::LayerPlan`): every read
/// is bounded by `extent` inside the store and every write by the frame, before it is queued.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ComposeLayer {
    /// Store offset of the first byte the kernel addresses.
    pub src: u64,
    /// Bytes from `src` the kernel may read.
    pub extent: u64,
    /// Block-linear (else pitch).
    pub block_linear: bool,
    /// Pitch in bytes, or GOBs per row.
    pub pitch: u32,
    /// log2 GOBs per block.
    pub block_height_log2: u32,
    /// The rectangle's first byte column (block-linear).
    pub x0_bytes: u32,
    /// Its first row (block-linear).
    pub y0: u32,
    /// Pixels per row.
    pub width: u32,
    /// Rows.
    pub rows: u32,
    /// Output column in the frame.
    pub ox: u32,
    /// Output row.
    pub oy: u32,
    /// `bit0` alpha, `bit1` swap red/blue, `bit2` opaque, `bit3` XOR ([`COMPOSE_FLAGS`]; the
    /// mirror of `kf_disp::scanout::COMPOSE_*`, pinned equal by kf-qemu).
    pub flags: u32,
    /// Blend coefficients (see `kf_compose`).
    pub a_s: i32,
    /// See `a_s`.
    pub b_s: i32,
    /// See `a_s`.
    pub a_d: i32,
    /// See `a_s`.
    pub b_d: i32,
}

impl ComposeLayer {
    /// ⊘ The kernel's reads stay inside `extent` and its writes inside a `fw` x `fh` frame.
    fn check(&self, fw: u32, fh: u32) -> Result<(), String> {
        let l = *self;
        let fits = |a: u32, n: u32, room: u32| u64::from(a) + u64::from(n) <= u64::from(room);
        if l.rows == 0 || l.width == 0 || l.rows > 16384 || l.width > 16384 {
            return Err(format!("{l:?} is not a composable rectangle"));
        }
        if !fits(l.ox, l.width, fw) || !fits(l.oy, l.rows, fh) {
            return Err(format!("{l:?} leaves the {fw}x{fh} frame"));
        }
        if l.flags & !COMPOSE_FLAGS != 0 {
            return Err(format!("{l:?}: flag bits the kernel does not know"));
        }
        let row = u64::from(l.width) * 4;
        let need = if l.block_linear {
            if l.block_height_log2 > 5
                || !l.x0_bytes.is_multiple_of(4)
                || u64::from(l.x0_bytes) + row > u64::from(l.pitch) * 64
            {
                return Err(format!("{l:?}: the rows leave the surface's GOB columns"));
            }
            (u64::from(l.y0) + u64::from(l.rows)).div_ceil(8u64 << l.block_height_log2)
                * u64::from(l.pitch)
                * (512u64 << l.block_height_log2)
        } else {
            if u64::from(l.pitch) < row {
                return Err(format!("{l:?}: a row is wider than the pitch"));
            }
            u64::from(l.rows - 1) * u64::from(l.pitch) + row
        };
        if need > l.extent {
            return Err(format!("{l:?}: the rows need {need:#x} bytes"));
        }
        Ok(())
    }
}

/// ★ One semi-planar YUV window's program (the mirror of `kf_disp::scanout::YuvPlan`): every read is
/// bounded by the two extents inside the store and every write by the frame, before it is queued.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct YuvLayer {
    /// Store offset and readable bytes of the luma plane.
    pub y_src: u64,
    /// See `y_src`.
    pub y_extent: u64,
    /// Store offset and readable bytes of the chroma plane.
    pub c_src: u64,
    /// See `c_src`.
    pub c_extent: u64,
    /// Block-linear (else pitch), both planes.
    pub block_linear: bool,
    /// Luma pitch in bytes (pitch) or GOBs per row (block-linear).
    pub y_pitch: u32,
    /// Chroma pitch, likewise.
    pub c_pitch: u32,
    /// log2 GOBs per block.
    pub block_height_log2: u32,
    /// Source rectangle origin and size (luma pixels).
    pub sx0: u32,
    /// See `sx0`.
    pub sy0: u32,
    /// See `sx0`.
    pub sw: u32,
    /// See `sx0`.
    pub sh: u32,
    /// Destination rectangle in the frame.
    pub ox: u32,
    /// See `ox`.
    pub oy: u32,
    /// See `ox`.
    pub dw: u32,
    /// See `ox`.
    pub dh: u32,
    /// log2 chroma subsampling.
    pub sub_x_log2: u32,
    /// See `sub_x_log2`.
    pub sub_y_log2: u32,
    /// The chroma pair is V then U.
    pub vu_first: bool,
}

impl YuvLayer {
    /// ⊘ Re-derive, independently of the planner, that the kernel's reads stay inside the extents
    /// and its writes inside the `fw` x `fh` frame.
    fn check(&self, fw: u32, fh: u32) -> Result<(), String> {
        let l = *self;
        let fits = |a: u32, n: u32, room: u32| u64::from(a) + u64::from(n) <= u64::from(room);
        if l.sw == 0 || l.sh == 0 || l.dw == 0 || l.dh == 0 || l.dw > 16384 || l.dh > 16384 {
            return Err(format!("{l:?} is not a composable rectangle"));
        }
        if l.sw > 16384 || l.sh > 16384 || l.sub_x_log2 > 1 || l.sub_y_log2 > 1 {
            return Err(format!("{l:?}: source geometry outside the kernel's range"));
        }
        if !fits(l.ox, l.dw, fw) || !fits(l.oy, l.dh, fh) {
            return Err(format!("{l:?} leaves the {fw}x{fh} frame"));
        }
        let x_end = u64::from(l.sx0) + u64::from(l.sw);
        let y_end = u64::from(l.sy0) + u64::from(l.sh);
        let (cx_end, cy_end) = (
            x_end.div_ceil(1 << l.sub_x_log2),
            y_end.div_ceil(1 << l.sub_y_log2),
        );
        let need = |pitch: u32, bpp: u64, xe: u64, ye: u64| -> Result<u64, String> {
            if l.block_linear {
                if l.block_height_log2 > 5 || xe * bpp > u64::from(pitch) * 64 || pitch == 0 {
                    return Err(format!("{l:?}: the row leaves the surface's GOB columns"));
                }
                Ok(ye.div_ceil(8u64 << l.block_height_log2)
                    * u64::from(pitch)
                    * (512u64 << l.block_height_log2))
            } else {
                if xe * bpp > u64::from(pitch) {
                    return Err(format!("{l:?}: a row is wider than the pitch"));
                }
                Ok((ye - 1) * u64::from(pitch) + xe * bpp)
            }
        };
        if need(l.y_pitch, 1, x_end, y_end)? > l.y_extent
            || need(l.c_pitch, 2, cx_end, cy_end)? > l.c_extent
        {
            return Err(format!(
                "{l:?}: the planes need more bytes than their extents"
            ));
        }
        Ok(())
    }
}

impl std::fmt::Debug for DisplayGpu {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("DisplayGpu")
            .field("device", &self.device)
            .field("store_bytes", &self.store.map(|s| s.1))
            .finish()
    }
}

fn refused(what: &'static str, name: String) -> CudaError {
    CudaError::Refused {
        what,
        code: 0,
        name,
    }
}

impl DisplayGpu {
    /// Bring up a context on the GPU at PCI address `bdf` (the device's host GPU, never ordinal 0).
    ///
    /// # Errors
    /// [`CudaError`], by name.
    pub fn bring_up_on(bdf: &str) -> Result<DisplayGpu, CudaError> {
        let cu = Cuda::open()?;
        cu.init()?;
        let device = cu.device_by_pci_bus_id(bdf)?;
        let ctx = cu.ctx_create(device)?;
        let stream = cu.stream_create()?;
        let done = CompletionFd::new()?;
        let mut ptx = SCANOUT_PTX.to_vec();
        ptx.push(0);
        let compose = cu
            .module_load(&ptx)
            .and_then(|m| cu.module_function(m, COMPOSE_ENTRY))
            .map_err(|e| format!("the compose kernel did not load: {e}"));
        let mut pack_ptx = PACK_PTX.to_vec();
        pack_ptx.push(0);
        let pack = cu
            .module_load(&pack_ptx)
            .and_then(|m| cu.module_function(m, PACK_ENTRY))
            .map_err(|e| format!("the pack kernel did not load: {e}"));
        let mut sum_ptx = SUM_PTX.to_vec();
        sum_ptx.push(0);
        let sum = cu
            .module_load(&sum_ptx)
            .and_then(|m| cu.module_function(m, SUM_ENTRY))
            .map_err(|e| format!("the checksum kernel did not load: {e}"));
        let mut color_ptx = COLOR_PTX.to_vec();
        color_ptx.push(0);
        let color = cu
            .module_load(&color_ptx)
            .and_then(|m| {
                Ok([
                    cu.module_function(m, "kf_color_compose")?,
                    cu.module_function(m, "kf_color_output")?,
                    cu.module_function(m, "kf_color_validate")?,
                    cu.module_function(m, "kf_tmo_validate")?,
                ])
            })
            .map_err(|e| format!("the SDR colour kernels did not load: {e}"));
        let mut yuv_ptx = YUV_PTX.to_vec();
        yuv_ptx.push(0);
        let yuv = cu
            .module_load(&yuv_ptx)
            .and_then(|m| {
                Ok([
                    cu.module_function(m, YUV_ENTRY)?,
                    cu.module_function(m, YUV_COLOR_ENTRY)?,
                ])
            })
            .map_err(|e| format!("the YUV kernel did not load: {e}"));
        let color_event = cu.event_create()?;
        let signal_event = cu.event_create()?;
        Ok(DisplayGpu {
            cu,
            ctx,
            device,
            store: None,
            stream,
            done,
            compose,
            staging: None,
            pack,
            slots: Vec::new(),
            sum,
            sums: None,
            color,
            yuv,
            color_frame: None,
            color_luts: None,
            color_pipelines: None,
            color_status: None,
            color_event,
            color_recorded: false,
            color_snapshots: [None; 65],
            signal_event,
        })
    }

    /// Why the checksum kernel is unavailable, if it is (the worker logs it once and sends every
    /// check).
    #[must_use]
    pub fn checksum_refused(&self) -> Option<&str> {
        self.sum.as_ref().err().map(String::as_str)
    }

    /// ★ `display-max-fps` (D2): queue the checksum of the `w` x `h` composition begun by
    /// [`Self::compose_begin`] — the row slots zeroed, `kf_sum` over the staging frame (one CTA per
    /// row), the row sums copied back to page-locked memory — on the display stream, without the
    /// signal. [`Self::checksum_rows`] reads them once the frame's completion was observed.
    ///
    /// ⊘ Bounds, here and not in the kernel: the frame lies inside the staging allocation
    /// (`rows x 4w` bytes are read), and the row buffers hold `h` sums (`h x 8` bytes written).
    ///
    /// # Errors
    /// Refused by name: no kernel, no composition, a frame larger than the staging one; the CUDA
    /// error.
    pub fn compose_checksum(&mut self, w: u32, h: u32) -> Result<(), CudaError> {
        let what = "DisplayGpu::compose_checksum";
        let f = *self.sum.as_ref().map_err(|e| refused(what, e.clone()))?;
        let Some((src, len)) = self.staging else {
            return Err(refused(what, "no composition was begun".into()));
        };
        let n = usize::try_from(u64::from(w) * u64::from(h) * 4)
            .map_err(|_| refused(what, format!("{w}x{h}")))?;
        if w == 0 || h == 0 || n > len {
            return Err(refused(
                what,
                format!("a {w}x{h} frame in a {len:#x}-byte staging frame"),
            ));
        }
        let rows = h as usize;
        if self.sums.as_ref().is_none_or(|s| s.2 < rows) {
            if let Some((p, host, _)) = self.sums.take() {
                // the stream drains first: a queued checksum may still write either buffer
                self.cu.ctx_synchronize()?;
                self.cu.mem_free(p);
                self.cu
                    .pinned_free(host, "cuMemFreeHost(display checksum)")?;
            }
            let dev = self
                .cu
                .mem_alloc_zeroed(rows * 8, "cuMemAlloc(display checksum)")?;
            let host = match self
                .cu
                .pinned_alloc(rows * 8, "cuMemAllocHost(display checksum)")
            {
                Ok(h) => h,
                Err(e) => {
                    self.cu.mem_free(dev);
                    return Err(e);
                }
            };
            self.sums = Some((dev, host, rows));
        }
        let Some((dev, host, _)) = self.sums.as_ref() else {
            return Err(refused(what, "no row buffer".into()));
        };
        self.cu.memset_d8_async(
            self.stream,
            *dev,
            0,
            rows * 8,
            "cuMemsetD8Async(display checksum)",
        )?;
        let u = |x: u32| x.to_le_bytes().to_vec();
        let mut params = vec![
            src.to_le_bytes().to_vec(),
            dev.to_le_bytes().to_vec(),
            u(w),
            u(w * 4),
        ];
        self.cu
            .launch_args(self.stream, f, h, SUM_THREADS, 0, &mut params, what)?;
        self.cu.memcpy_d2h_async(
            self.stream,
            host,
            0,
            *dev,
            rows * 8,
            "cuMemcpyDtoHAsync(display checksum)",
        )
    }

    /// ★ The row sums the last [`Self::compose_checksum`] of an `h`-row frame copied back (fold
    /// them with `kf_disp::pace::digest`). ⊘ Only after the completion signal queued behind it was
    /// observed: before, the bytes are still being written by DMA.
    ///
    /// # Errors
    /// Refused when no checksum of that many rows was queued.
    pub fn checksum_rows(&self, h: u32) -> Result<Vec<u64>, CudaError> {
        let what = "DisplayGpu::checksum_rows";
        let rows = h as usize;
        let Some((_, host, cap)) = self.sums.as_ref().filter(|s| s.2 >= rows && rows > 0) else {
            return Err(refused(what, format!("no checksum of {h} rows was queued")));
        };
        debug_assert!(*cap >= rows);
        Ok(host
            .read(0, rows * 8)
            .as_chunks::<8>()
            .0
            .iter()
            .map(|c| u64::from_le_bytes(*c))
            .collect())
    }

    /// Allocate a page-locked frame of `len` bytes in this context.
    ///
    /// # Errors
    /// [`CudaError`]; a zero length is refused.
    pub fn frame(&self, len: usize) -> Result<Frame, CudaError> {
        if len == 0 {
            return Err(refused("DisplayGpu::frame", "a zero-length frame".into()));
        }
        self.make_current()?;
        Ok(Frame {
            buf: self.cu.pinned_alloc(len, "cuMemAllocHost(display frame)")?,
            map: None,
        })
    }

    /// ★ A frame over `map` (the display broker's sealed memfd, mapped by the caller), page-locked
    /// with `cuMemHostRegister` so the scanout copy lands in the pages the broker reads.
    ///
    /// # Errors
    /// The CUDA refusal — a driver without the entry, or one that will not pin these pages — with
    /// the mapping handed back.
    pub fn frame_over(
        &self,
        map: kf_linux_raw::MappedRegion,
    ) -> Result<Frame, (CudaError, kf_linux_raw::MappedRegion)> {
        if let Err(e) = self.make_current() {
            return Err((e, map));
        }
        match self
            .cu
            .host_register(&map.host_span(), "cuMemHostRegister(display broker frame)")
        {
            Ok(buf) => Ok(Frame {
                buf,
                map: Some(map),
            }),
            Err(e) => Err((e, map)),
        }
    }

    /// The fd that becomes readable when a queued scanout copy completed (the worker polls it).
    #[must_use]
    pub fn completion_fd(&self) -> &CompletionFd {
        &self.done
    }

    /// ★ Give a frame back (`cuMemFreeHost`). ⊘ Only once no queued copy targets it and the console
    /// no longer reads it — the caller's frame state machine decides that, never this binding.
    ///
    /// # Errors
    /// [`CudaError`].
    pub fn release_frame(&self, mut f: Frame) -> Result<(), CudaError> {
        self.make_current()?;
        let buf = std::mem::replace(&mut f.buf, PinnedBuf::empty());
        match f.map.take() {
            // unregister first, and the mapping goes only once that succeeded
            Some(map) => {
                let r = self
                    .cu
                    .host_unregister(buf, "cuMemHostUnregister(display broker frame)");
                if r.is_ok() {
                    drop(map);
                } else {
                    std::mem::forget(map);
                }
                r
            }
            None => self.cu.pinned_free(buf, "cuMemFreeHost(display frame)"),
        }
    }

    /// ★ Start a `w` x `h` composition: the device staging frame (grown when too small) cleared to
    /// black on the display stream — what no window covers is black, as on a real head.
    ///
    /// # Errors
    /// [`CudaError`]; an empty or oversized frame is refused.
    pub fn compose_begin(&mut self, w: u32, h: u32) -> Result<(), CudaError> {
        let what = "DisplayGpu::compose_begin";
        let n = usize::try_from(u64::from(w) * u64::from(h) * 4)
            .map_err(|_| refused(what, format!("{w}x{h}")))?;
        if n == 0 || w > 16384 || h > 16384 {
            return Err(refused(what, format!("a {w}x{h} frame")));
        }
        if self.staging.is_none_or(|(_, len)| len < n) {
            if let Some((p, _)) = self.staging.take() {
                // the stream drains first: a queued compose may still write the old staging
                self.cu.ctx_synchronize()?;
                self.cu.mem_free(p);
            }
            self.staging = Some((
                self.cu.mem_alloc_zeroed(n, "cuMemAlloc(display staging)")?,
                n,
            ));
        }
        let (p, _) = self.staging.unwrap_or((0, 0));
        self.cu
            .memset_d8_async(self.stream, p, 0, n, "cuMemsetD8Async(display staging)")
    }

    /// ★ Queue window `l` of the composition begun by [`Self::compose_begin`] (`w` x `h`).
    ///
    /// # Errors
    /// Refused by name when the kernel did not load, a read would leave the store or the layer's
    /// extent, or a write the frame; the CUDA error otherwise.
    pub fn compose_layer(&self, l: &ComposeLayer, w: u32, h: u32) -> Result<(), CudaError> {
        let what = "DisplayGpu::compose_layer";
        l.check(w, h).map_err(|e| refused(what, e))?;
        let n = usize::try_from(l.extent).map_err(|_| refused(what, format!("{l:?}")))?;
        let src = self.at(l.src, n, what)?;
        self.launch_compose(src, l, w, h, what)
    }

    /// ★ Is the YUV kernel loaded? (When not, the console copy leaves YUV windows out, by name.)
    ///
    /// # Errors
    /// Why it did not load.
    pub fn yuv_ready(&self) -> Result<(), String> {
        self.yuv.as_ref().map(|_| ()).map_err(Clone::clone)
    }

    /// ★ Queue one semi-planar YUV window onto the composition begun by [`Self::compose_begin`]
    /// (opaque, after whatever was composed before it).
    ///
    /// # Errors
    /// Refused by name when the kernel did not load, a read would leave a plane's extent or the
    /// store, or a write the frame; the CUDA error otherwise.
    pub fn compose_yuv(&self, l: &YuvLayer, w: u32, h: u32) -> Result<(), CudaError> {
        let what = "DisplayGpu::compose_yuv";
        let f = self.yuv.as_ref().map_err(|e| refused(what, e.clone()))?[0];
        l.check(w, h).map_err(|e| refused(what, e))?;
        let Some((dst, _)) = self.staging else {
            return Err(refused(what, "no composition was begun".into()));
        };
        self.launch_yuv(f, dst, l, w, h, what)
    }

    /// ★ The same window into the colour composition's FP32 frame ([`Self::color_begin`]), in its
    /// place in the back-to-front order (opaque; the window's own colour pipeline is not applied).
    ///
    /// # Errors
    /// As [`Self::compose_yuv`].
    pub fn color_yuv(&self, l: &YuvLayer, w: u32, h: u32) -> Result<(), CudaError> {
        let what = "DisplayGpu::color_yuv";
        let f = self.yuv.as_ref().map_err(|e| refused(what, e.clone()))?[1];
        l.check(w, h).map_err(|e| refused(what, e))?;
        let (dst, len) = self
            .color_frame
            .ok_or_else(|| refused(what, "no colour frame".into()))?;
        if u64::from(w) * u64::from(h) * 16 > len as u64 {
            return Err(refused(what, "colour frame is too small".into()));
        }
        self.launch_yuv(f, dst, l, w, h, what)
    }

    fn launch_yuv(
        &self,
        f: Func,
        dst: CUdeviceptr,
        l: &YuvLayer,
        w: u32,
        h: u32,
        what: &'static str,
    ) -> Result<(), CudaError> {
        let ny = usize::try_from(l.y_extent).map_err(|_| refused(what, format!("{l:?}")))?;
        let nc = usize::try_from(l.c_extent).map_err(|_| refused(what, format!("{l:?}")))?;
        let ys = self.at(l.y_src, ny, what)?;
        let cs = self.at(l.c_src, nc, what)?;
        let u = |x: u32| x.to_le_bytes().to_vec();
        let mut params = vec![
            ys.to_le_bytes().to_vec(),
            cs.to_le_bytes().to_vec(),
            dst.to_le_bytes().to_vec(),
            u(u32::from(l.block_linear)),
            u(l.y_pitch),
            u(l.c_pitch),
            u(l.block_height_log2),
            u(l.sx0),
            u(l.sy0),
            u(l.sw),
            u(l.sh),
            u(l.ox),
            u(l.oy),
            u(l.dw),
            u(l.dh),
            u(w),
            u(h),
            u(l.sub_x_log2),
            u(l.sub_y_log2),
            u(u32::from(l.vu_first)),
        ];
        self.cu
            .launch_args(self.stream, f, l.dh, 256, 0, &mut params, what)
    }

    /// Begin a colour composition, retaining FP16 values in an FP32 container until output.
    /// All operations are on the display worker's stream, away from the vCPU.
    pub fn color_begin(&mut self, w: u32, h: u32) -> Result<(), CudaError> {
        self.color_recorded = false;
        let what = "DisplayGpu::color_begin";
        if u64::from(w) * u64::from(h) > 3840 * 2160 {
            return Err(refused(
                what,
                "SDR frame exceeds fixed 4K pixel ceiling".into(),
            ));
        }
        self.color.as_ref().map_err(|e| refused(what, e.clone()))?;
        self.compose_begin(w, h)?;
        let n = w as usize * h as usize * 16;
        if self.color_frame.is_none_or(|(_, len)| len < n) {
            if let Some((p, _)) = self.color_frame.take() {
                self.cu.ctx_synchronize()?;
                self.cu.mem_free(p);
            }
            self.color_frame = Some((self.cu.mem_alloc_zeroed(n, what)?, n));
        }
        if self.color_luts.is_none() {
            self.color_luts = Some(self.cu.mem_alloc_zeroed(65 * COLOR_LUT_BYTES, what)?);
        }
        if self.color_pipelines.is_none() {
            self.color_pipelines = Some(self.cu.mem_alloc_zeroed(32 * COLOR_PIPELINE_BYTES, what)?);
        }
        if self.color_status.is_none() {
            let dev = self.cu.mem_alloc_zeroed(4, what)?;
            match self.cu.pinned_alloc(4, what) {
                Ok(host) => self.color_status = Some((dev, host)),
                Err(e) => {
                    self.cu.mem_free(dev);
                    return Err(e);
                }
            }
        }
        let (frame, _) = self
            .color_frame
            .ok_or_else(|| refused(what, "missing colour frame".into()))?;
        let (status, _) = self
            .color_status
            .as_ref()
            .ok_or_else(|| refused(what, "missing colour status".into()))?;
        self.cu.memset_d8_async(self.stream, *status, 0, 4, what)?;
        self.cu.memset_d8_async(self.stream, frame, 0, n, what)
    }

    fn color_snapshot(
        &mut self,
        slot: u32,
        lut: Option<ColorLut>,
        input: bool,
    ) -> Result<CUdeviceptr, CudaError> {
        let what = "DisplayGpu::color_snapshot";
        let Some(lut) = lut else {
            return Ok(0);
        };
        if slot > 64 {
            return Err(refused(what, "LUT slot outside fixed allocation".into()));
        }
        if !(65..=1025).contains(&lut.entries)
            || ((input || slot == 64) && ![257, 1025].contains(&lut.entries))
        {
            return Err(refused(
                what,
                "LUT sample count outside supported extent".into(),
            ));
        }
        let bytes = (lut.entries as usize + 4) * 8;
        let src = self.at(lut.src, bytes, what)?;
        let base = self
            .color_luts
            .ok_or_else(|| refused(what, "no LUT allocation".into()))?;
        let dst = base + u64::from(slot) * COLOR_LUT_BYTES as u64;
        let key = (lut.src, lut.interpolate, lut.token, lut.entries);
        if self.color_snapshots[slot as usize]
            .is_none_or(|old| (old.src, old.interpolate, old.token, old.entries) != key)
        {
            self.cu
                .memcpy_d2d_async(self.stream, dst, src, bytes, what)?;
            self.color_snapshots[slot as usize] = Some(lut);
        }
        if input {
            let f = self.color.as_ref().map_err(|e| refused(what, e.clone()))?[2];
            let status = self
                .color_status
                .as_ref()
                .ok_or_else(|| refused(what, "no validation status".into()))?
                .0;
            let mut args = vec![
                dst.to_le_bytes().to_vec(),
                lut.entries.to_le_bytes().to_vec(),
                status.to_le_bytes().to_vec(),
            ];
            self.cu
                .launch_args(self.stream, f, 5, 256, 0, &mut args, what)?;
        }
        Ok(dst)
    }

    /// Snapshot and compose one RGB8888 window using its FP16 input table.
    /// Convenience entry for SDR fixtures with the remaining stages bypassed.
    pub fn color_layer(
        &mut self,
        slot: u32,
        l: &ComposeLayer,
        lut: Option<ColorLut>,
        w: u32,
        h: u32,
    ) -> Result<(), CudaError> {
        self.color_pipeline_layer(slot, l, lut, None, None, w, h)
    }

    /// Run the complete authored pre-composition program on the GPU. TMO snapshots
    /// use separate slots; no source reread or fabricated GPU completion is introduced.
    #[allow(clippy::too_many_arguments)]
    pub fn color_pipeline_layer(
        &mut self,
        slot: u32,
        l: &ComposeLayer,
        lut: Option<ColorLut>,
        tmo: Option<ColorLut>,
        pipeline: Option<&ColorPipeline>,
        w: u32,
        h: u32,
    ) -> Result<(), CudaError> {
        let what = "DisplayGpu::color_layer";
        l.check(w, h).map_err(|e| refused(what, e))?;
        if slot >= 32 || l.flags & 8 != 0 {
            return Err(refused(
                what,
                "window slot or XOR outside SDR subset".into(),
            ));
        }
        let src = self.at(
            l.src,
            usize::try_from(l.extent).map_err(|_| refused(what, "layer extent".into()))?,
            what,
        )?;
        let bytes = u64::from(w) * u64::from(h) * 16;
        let (dst, len) = self
            .color_frame
            .ok_or_else(|| refused(what, "no colour frame".into()))?;
        if bytes > len as u64 {
            return Err(refused(what, "colour frame is too small".into()));
        }
        let p = self.color_snapshot(slot, lut, true)?;
        let tone = self.color_snapshot(32 + slot, tmo, false)?;
        if let Some(tmo) = tmo {
            let f = self.color.as_ref().map_err(|e| refused(what, e.clone()))?[3];
            let status = self
                .color_status
                .as_ref()
                .ok_or_else(|| refused(what, "missing status".into()))?
                .0;
            let mut args = vec![
                tone.to_le_bytes().to_vec(),
                tmo.entries.to_le_bytes().to_vec(),
                status.to_le_bytes().to_vec(),
            ];
            self.cu
                .launch_args(self.stream, f, 5, 256, 0, &mut args, what)?;
        }
        let program = if let Some(pipeline) = pipeline {
            let bytes = pipeline.bytes().map_err(|e| refused(what, e))?;
            let address = self
                .color_pipelines
                .ok_or_else(|| refused(what, "missing pipeline allocation".into()))?
                + u64::from(slot) * COLOR_PIPELINE_BYTES as u64;
            self.cu.memcpy_h2d(address, &bytes, what)?;
            address
        } else {
            0
        };
        let f = self.color.as_ref().map_err(|e| refused(what, e.clone()))?[0];
        let u = |v: u32| v.to_le_bytes().to_vec();
        let i = |v: i32| v.to_le_bytes().to_vec();
        let mut args = vec![
            src.to_le_bytes().to_vec(),
            dst.to_le_bytes().to_vec(),
            u(u32::from(l.block_linear)),
            u(l.pitch),
            u(l.block_height_log2),
            u(l.x0_bytes),
            u(l.y0),
            u(l.width),
            u(l.ox),
            u(l.oy),
            u(w),
            u(h),
            u(l.flags),
            i(l.a_s),
            i(l.b_s),
            i(l.a_d),
            i(l.b_d),
            p.to_le_bytes().to_vec(),
            u(u32::from(lut.is_some_and(|v| v.interpolate))),
            u(lut.map_or(0, |v| v.entries)),
            tone.to_le_bytes().to_vec(),
            u(u32::from(tmo.is_some_and(|v| v.interpolate))),
            u(tmo.map_or(0, |v| v.entries)),
            program.to_le_bytes().to_vec(),
            self.color_status
                .as_ref()
                .ok_or_else(|| refused(what, "missing status".into()))?
                .0
                .to_le_bytes()
                .to_vec(),
        ];
        self.cu
            .launch_args(self.stream, f, l.rows, 256, 0, &mut args, what)
    }

    /// Apply the authored CSC coefficients and the fixed-point output table to the full head.
    /// The validation result is copied back on this same stream, before the frame's signal.
    pub fn color_output(
        &mut self,
        w: u32,
        h: u32,
        lut: Option<ColorLut>,
        matrix: &[i32; 12],
    ) -> Result<(), CudaError> {
        let what = "DisplayGpu::color_output";
        let (src, slen) = self
            .color_frame
            .ok_or_else(|| refused(what, "no colour frame".into()))?;
        let (dst, dlen) = self
            .staging
            .ok_or_else(|| refused(what, "no output frame".into()))?;
        let pixels = u64::from(w) * u64::from(h);
        if w == 0 || h == 0 || pixels * 16 > slen as u64 || pixels * 4 > dlen as u64 {
            return Err(refused(what, "colour output exceeds frame".into()));
        }
        let p = self.color_snapshot(64, lut, false)?;
        let f = self.color.as_ref().map_err(|e| refused(what, e.clone()))?[1];
        let mut args = vec![
            src.to_le_bytes().to_vec(),
            dst.to_le_bytes().to_vec(),
            w.to_le_bytes().to_vec(),
            p.to_le_bytes().to_vec(),
            u32::from(lut.is_some_and(|v| v.interpolate))
                .to_le_bytes()
                .to_vec(),
            matrix.iter().flat_map(|v| v.to_le_bytes()).collect(),
            lut.map_or(0, |v| v.entries).to_le_bytes().to_vec(),
        ];
        self.cu
            .launch_args(self.stream, f, h, 256, 0, &mut args, what)?;
        let (dev, host) = self
            .color_status
            .as_ref()
            .ok_or_else(|| refused(what, "no validation status".into()))?;
        self.cu
            .memcpy_d2h_async(self.stream, host, 0, *dev, 4, what)?;
        self.cu.event_record(self.color_event, self.stream)?;
        self.color_recorded = true;
        Ok(())
    }

    /// Read only after the actual GPU completion signal. Never exposes LUT bytes to the CPU.
    pub fn color_verdict(&self) -> Result<(), String> {
        if !self.color_recorded
            || !self
                .cu
                .event_query(self.color_event)
                .map_err(|e| e.to_string())?
        {
            return Err("colour validation has not completed on the GPU".into());
        }
        let (_, host) = self
            .color_status
            .as_ref()
            .ok_or("no colour validation result")?;
        let b = host.read(0, 4);
        if b == [0, 0, 0, 0] {
            Ok(())
        } else {
            Err(if b[0] & 1 != 0 {
                "input LUT has non-SDR FP16 entries"
            } else if b[0] & 2 != 0 {
                "TMO LUT has unsupported VSS header or unequal intensity channels"
            } else {
                "CSC program produced nonfinite FP16"
            }
            .into())
        }
    }

    /// ★ End the composition: the staging frame is copied into `dst` (tight, `w * 4` bytes a row),
    /// then the host signal on [`Self::completion_fd`]. Only the GPU moves the bytes.
    ///
    /// # Errors
    /// Refused by name when the frame is smaller than the composition; the CUDA error otherwise.
    pub fn compose_finish(&self, w: u32, h: u32, dst: &Frame) -> Result<(), CudaError> {
        self.compose_to_host(w, h, dst)?;
        self.compose_signal()
    }

    /// ★ The host signal on [`Self::completion_fd`], after whatever the frame's last operation
    /// was (the D2H copy, the pack, or both) — queued once per frame.
    ///
    /// # Errors
    /// The CUDA error.
    pub fn compose_signal(&self) -> Result<(), CudaError> {
        self.cu.event_record(self.signal_event, self.stream)?;
        self.cu.launch_host_signal(self.stream, &self.done)
    }

    /// ★ 2026-10-08 (`V3_DISPLAY.md` §8.18): the state of the work before the last
    /// [`Self::compose_signal`] — **never blocks**. `Ok(false)`: still queued (the GPU, or the host
    /// RM in front of it, has not run it yet); `Ok(true)`: done, its signal is on its way; `Err`:
    /// the stream failed, by name — the only answer that means the completion will never come.
    ///
    /// # Errors
    /// The CUDA error the stream reports.
    pub fn signal_state(&self) -> Result<bool, CudaError> {
        self.cu.event_query(self.signal_event)
    }

    /// ★ The staging frame's D2H copy into `dst` (tight, `w * 4` bytes a row), without the signal
    /// — the host-RAM rungs and the console.
    ///
    /// # Errors
    /// Refused by name when the frame is smaller than the composition; the CUDA error otherwise.
    pub fn compose_to_host(&self, w: u32, h: u32, dst: &Frame) -> Result<(), CudaError> {
        let what = "DisplayGpu::compose_to_host";
        let n = usize::try_from(u64::from(w) * u64::from(h) * 4)
            .map_err(|_| refused(what, format!("{w}x{h}")))?;
        let Some((p, len)) = self.staging else {
            return Err(refused(what, "no composition was begun".into()));
        };
        if n > len || n > dst.len() {
            return Err(refused(what, format!("{n:#x} bytes do not fit")));
        }
        self.cu.memcpy_d2h_async(
            self.stream,
            &dst.buf,
            0,
            p,
            n,
            "cuMemcpyDtoHAsync(display frame)",
        )
    }

    /// ★ The GPU-copy rung: the staging frame PACKED into slot `slot` (block-linear, `pack`'s
    /// geometry), without the signal. No byte crosses PCIe. The bounds are [`BlPack::check`]'s,
    /// against this slot's own length and the staging frame's.
    ///
    /// # Errors
    /// Refused by name: no pack kernel, an unknown slot, no composition, a bound; the CUDA error.
    pub fn compose_to_slot(&self, slot: SlotId, pack: &BlPack) -> Result<(), CudaError> {
        let what = "DisplayGpu::compose_to_slot";
        let Some((src, staging_bytes)) = self.staging else {
            return Err(refused(what, "no composition was begun".into()));
        };
        self.launch_pack(src, staging_bytes as u64, slot, pack, what)
    }

    /// The pack launch: [`BlPack::check`] first, then `ceil(gobs / 8)` CTAs of 256 threads.
    fn launch_pack(
        &self,
        src: CUdeviceptr,
        src_bytes: u64,
        slot: SlotId,
        pack: &BlPack,
        what: &'static str,
    ) -> Result<(), CudaError> {
        let f = *self.pack.as_ref().map_err(|e| refused(what, e.clone()))?;
        let Some(&(dst, bytes)) = self.slots.get(slot.0) else {
            return Err(refused(what, format!("{slot:?} was never imported")));
        };
        pack.check(bytes, src_bytes).map_err(|e| refused(what, e))?;
        let grid = u32::try_from(pack.gobs.div_ceil(u64::from(PACK_THREADS / 32)))
            .map_err(|_| refused(what, format!("{pack:?}: too many GOBs")))?;
        let u = |x: u32| x.to_le_bytes().to_vec();
        let mut params = vec![
            src.to_le_bytes().to_vec(),
            dst.to_le_bytes().to_vec(),
            u(pack.width),
            u(pack.height),
            u(pack.gobs_per_row),
            u(pack.h_log2),
            pack.gobs.to_le_bytes().to_vec(),
            u(pack.bits[0]),
            u(pack.bits[1]),
            u(pack.bits[2]),
            u(pack.bits[3]),
            u(pack.bits[4]),
        ];
        self.cu
            .launch_args(self.stream, f, grid, PACK_THREADS, 0, &mut params, what)
    }

    /// ★ Import a display slot — the RM object `fd` (an `/dev/nvidiactl` descriptor RM exported it
    /// on) of `bytes` bytes — into this context, exactly as the store is imported. `bytes` must be
    /// whole 2 MiB granules (CUDA maps imports in its allocation granularity).
    ///
    /// # Errors
    /// Refused by name for a bad size; the import step that refused.
    pub fn import_slot(&mut self, fd: i32, bytes: u64) -> Result<SlotId, CudaError> {
        let what = "DisplayGpu::import_slot";
        if bytes == 0 || !bytes.is_multiple_of(2 << 20) || bytes > 64 << 20 {
            return Err(refused(what, format!("a {bytes:#x}-byte slot")));
        }
        self.make_current()?;
        let n = usize::try_from(bytes).map_err(|_| refused(what, format!("{bytes:#x}")))?;
        let p = self
            .cu
            .import_and_map(self.device, fd, n)
            .map_err(|name| CudaError::Refused {
                what: "cuMemImportFromShareableHandle + cuMemMap (display slot)",
                code: 0,
                name,
            })?;
        self.slots.push((p, bytes));
        Ok(SlotId(self.slots.len() - 1))
    }

    /// ★ Zero slot `slot` (synchronously) — before it is ever exported, so a compositor can never
    /// see what the previous tenant of that VRAM left.
    ///
    /// # Errors
    /// Refused for an unknown slot; the CUDA error.
    pub fn zero_slot(&self, slot: SlotId) -> Result<(), CudaError> {
        let what = "DisplayGpu::zero_slot";
        let Some(&(p, bytes)) = self.slots.get(slot.0) else {
            return Err(refused(what, format!("{slot:?} was never imported")));
        };
        let n = usize::try_from(bytes).map_err(|_| refused(what, format!("{bytes:#x}")))?;
        self.make_current()?;
        self.cu.memset_d8(p, 0, n, "cuMemsetD8(display slot)")
    }

    /// The bytes of slot `slot`.
    #[must_use]
    pub fn slot_bytes(&self, slot: SlotId) -> Option<u64> {
        self.slots.get(slot.0).map(|s| s.1)
    }

    /// ★ Bring-up self-test of the pack kernel on SYNTHETIC data, into a slot that has NOT been
    /// exported yet: `staging` (`4·w·h` bytes) is uploaded to scratch, packed into `slot`, and the
    /// slot's first `pack.gobs * 512` bytes come back for the caller to compare with
    /// `kf_disp::vramslot::pack_reference`. The slot is zeroed again afterwards.
    ///
    /// # Errors
    /// [`CudaError`]; a bound [`BlPack::check`] refuses.
    pub fn selftest_bl_pack(
        &mut self,
        slot: SlotId,
        staging: &[u8],
        pack: &BlPack,
    ) -> Result<Vec<u8>, CudaError> {
        let what = "DisplayGpu::selftest_bl_pack";
        self.make_current()?;
        let Some(&(p, bytes)) = self.slots.get(slot.0) else {
            return Err(refused(what, format!("{slot:?} was never imported")));
        };
        pack.check(bytes, staging.len() as u64)
            .map_err(|e| refused(what, e))?;
        let ext = usize::try_from(pack.gobs * 512).map_err(|_| refused(what, "extent".into()))?;
        let scratch = self
            .cu
            .mem_alloc_zeroed(staging.len(), "cuMemAlloc(pack selftest)")?;
        let out = (|| {
            self.cu
                .memcpy_h2d(scratch, staging, "cuMemcpyHtoD(pack selftest)")?;
            self.launch_pack(scratch, staging.len() as u64, slot, pack, what)?;
            self.cu.ctx_synchronize()?;
            let mut back = vec![0u8; ext];
            self.cu
                .memcpy_d2h(&mut back, p, "cuMemcpyDtoH(pack selftest)")?;
            Ok(back)
        })();
        self.cu.mem_free(scratch);
        let zeroed = self.zero_slot(slot);
        let out = out?;
        zeroed?;
        Ok(out)
    }

    /// The compose kernel launch (one CTA per row, 256 threads striding the row).
    fn launch_compose(
        &self,
        src: CUdeviceptr,
        l: &ComposeLayer,
        w: u32,
        h: u32,
        what: &'static str,
    ) -> Result<(), CudaError> {
        let f = *self
            .compose
            .as_ref()
            .map_err(|e| refused(what, e.clone()))?;
        let Some((dst, _)) = self.staging else {
            return Err(refused(what, "no composition was begun".into()));
        };
        let u = |x: u32| x.to_le_bytes().to_vec();
        let i = |x: i32| x.to_le_bytes().to_vec();
        let mut params = vec![
            src.to_le_bytes().to_vec(),
            dst.to_le_bytes().to_vec(),
            u(u32::from(l.block_linear)),
            u(l.pitch),
            u(l.block_height_log2),
            u(l.x0_bytes),
            u(l.y0),
            u(l.width),
            u(l.ox),
            u(l.oy),
            u(w * 4),
            u(w),
            u(h),
            u(l.flags),
            i(l.a_s),
            i(l.b_s),
            i(l.a_d),
            i(l.b_d),
        ];
        self.cu
            .launch_args(self.stream, f, l.rows, 256, 0, &mut params, what)
    }

    /// ★ Bring-up self-test of the compose kernel on SYNTHETIC data (never guest memory): upload
    /// `surface` to a scratch allocation, compose layer `l` (its `src` is ignored) into a `w` x `h`
    /// frame, wait, and return the frame's bytes — the caller compares them with the reference.
    ///
    /// # Errors
    /// [`CudaError`]; a layer that leaves `surface` or the frame is refused.
    pub fn selftest_compose(
        &mut self,
        surface: &[u8],
        l: &ComposeLayer,
        w: u32,
        h: u32,
    ) -> Result<Vec<u8>, CudaError> {
        let what = "DisplayGpu::selftest_compose";
        if l.extent > surface.len() as u64 {
            return Err(refused(what, format!("{l:?} leaves the synthetic surface")));
        }
        l.check(w, h).map_err(|e| refused(what, e))?;
        self.make_current()?;
        let len = usize::try_from(u64::from(w) * u64::from(h) * 4)
            .map_err(|_| refused(what, format!("{w}x{h}")))?;
        let scratch = self
            .cu
            .mem_alloc_zeroed(surface.len(), "cuMemAlloc(compose selftest)")?;
        let out = (|| {
            self.cu
                .memcpy_h2d(scratch, surface, "cuMemcpyHtoD(compose selftest)")?;
            let frame = self.frame(len)?;
            let run = self
                .compose_begin(w, h)
                .and_then(|()| self.launch_compose(scratch, l, w, h, what))
                .and_then(|()| {
                    let (p, _) = self.staging.unwrap_or((0, 0));
                    self.cu.memcpy_d2h_async(
                        self.stream,
                        &frame.buf,
                        0,
                        p,
                        len,
                        "cuMemcpyDtoHAsync(compose selftest)",
                    )
                })
                .and_then(|()| self.cu.ctx_synchronize());
            let bytes = run.map(|()| frame.read(0, len));
            let freed = self.release_frame(frame);
            let bytes = bytes?;
            freed?;
            Ok(bytes)
        })();
        self.cu.mem_free(scratch);
        out
    }

    /// Hardware oracle on synthetic fixtures only. The temporary store contains no
    /// guest data; table bytes are uploaded, snapshotted and transformed on the GPU.
    /// A rejected FP16 table returns an error before any fixture pixels are read.
    pub fn selftest_color(&mut self, fixture: &ColorFixture<'_>) -> Result<Vec<u8>, CudaError> {
        let what = "DisplayGpu::selftest_color";
        let ColorFixture {
            surface,
            input,
            output,
            layer,
            matrix,
            size: (w, h),
            ..
        } = *fixture;
        if ![261 * 8, COLOR_LUT_BYTES].contains(&input.len())
            || ![261 * 8, COLOR_LUT_BYTES].contains(&output.len())
            || surface.is_empty()
            || !surface.len().is_multiple_of(8)
            || layer.extent > surface.len() as u64
            || fixture.tone.is_some_and(|t| {
                !(69 * 8..=COLOR_LUT_BYTES).contains(&t.table.len())
                    || !t.table.len().is_multiple_of(8)
                    || t.mutate.is_some_and(|v| v.len() != t.table.len())
            })
            || fixture.mutate_input.is_some_and(|b| b.len() != input.len())
        {
            return Err(refused(what, "synthetic fixture extent".into()));
        }
        layer.check(w, h).map_err(|e| refused(what, e))?;
        self.make_current()?;
        self.cu.ctx_synchronize()?;
        let mut image = surface.to_vec();
        image.extend_from_slice(input);
        image.extend_from_slice(output);
        let tone_src = image.len() as u64;
        if let Some(tone) = fixture.tone {
            image.extend_from_slice(tone.table);
        }
        let scratch = self.cu.mem_alloc_zeroed(image.len(), what)?;
        let keep = self.store.replace((scratch, image.len() as u64));
        self.color_snapshots.fill(None);
        let run = (|| {
            self.cu.memcpy_h2d(scratch, &image, what)?;
            self.color_begin(w, h)?;
            let mut l = *layer;
            l.src = 0;
            let input_lut = Some(ColorLut {
                entries: (input.len() / 8 - 4) as u32,
                src: surface.len() as u64,
                interpolate: false,
                token: 1,
            });
            let tone_lut = fixture.tone.map(|t| ColorLut {
                entries: (t.table.len() / 8 - 4) as u32,
                src: tone_src,
                interpolate: true,
                token: 4,
            });
            self.color_pipeline_layer(
                0,
                &l,
                input_lut,
                tone_lut,
                fixture.tone.map(|t| t.pipeline),
                w,
                h,
            )?;
            if let Some(tone) = fixture.tone
                && let Some(new) = tone.mutate
            {
                self.cu.ctx_synchronize()?;
                self.cu.memcpy_h2d(scratch + tone_src, new, what)?;
                self.color_begin(w, h)?;
                self.color_pipeline_layer(
                    0,
                    &l,
                    input_lut,
                    Some(ColorLut {
                        entries: (tone.table.len() / 8 - 4) as u32,
                        src: tone_src,
                        interpolate: true,
                        token: if tone.rearm { 5 } else { 4 },
                    }),
                    Some(tone.pipeline),
                    w,
                    h,
                )?;
            }
            if let Some(new) = fixture.mutate_input {
                self.cu.ctx_synchronize()?;
                self.cu
                    .memcpy_h2d(scratch + surface.len() as u64, new, what)?;
                self.color_begin(w, h)?;
                self.color_layer(
                    0,
                    &l,
                    Some(ColorLut {
                        entries: (input.len() / 8 - 4) as u32,
                        src: surface.len() as u64,
                        interpolate: false,
                        token: if fixture.rearm { 3 } else { 1 },
                    }),
                    w,
                    h,
                )?;
            }
            self.color_output(
                w,
                h,
                Some(ColorLut {
                    entries: (output.len() / 8 - 4) as u32,
                    src: (surface.len() + input.len()) as u64,
                    interpolate: fixture.interpolate,
                    token: 2,
                }),
                matrix,
            )?;
            self.cu.ctx_synchronize()?;
            self.color_verdict().map_err(|e| refused(what, e))?;
            let frame = self.frame(w as usize * h as usize * 4)?;
            let copy = self.compose_to_host(w, h, &frame);
            let drained = self.cu.ctx_synchronize();
            if drained.is_err() {
                // A queued DMA may still name this pinned memory; keep it until
                // context destruction rather than freeing it on a lost completion.
                std::mem::forget(frame);
                drained?;
                unreachable!();
            }
            let bytes = copy.map(|()| frame.read(0, frame.len()));
            let freed = self.release_frame(frame);
            let bytes = bytes?;
            freed?;
            Ok(bytes)
        })();
        let drained = self.cu.ctx_synchronize();
        self.store = keep;
        self.color_snapshots.fill(None);
        // On a CUDA fault retain the scratch allocation until context destruction.
        if drained.is_ok() {
            self.cu.mem_free(scratch);
        }
        let bytes = run?;
        drained?;
        Ok(bytes)
    }

    /// Make this context current on the calling thread (the worker calls it once, at its top).
    ///
    /// # Errors
    /// [`CudaError`].
    pub fn make_current(&self) -> Result<(), CudaError> {
        self.cu.ctx_set_current(self.ctx)
    }

    /// Import the RM-exported store (`fd` on `/dev/nvidiactl`, `bytes` long) into this context.
    ///
    /// # Errors
    /// [`CudaError`], naming the import step that refused; a second import is refused.
    pub fn import_store(&mut self, fd: i32, bytes: u64) -> Result<(), CudaError> {
        if self.store.is_some() {
            return Err(refused(
                "DisplayGpu::import_store",
                "a store is already imported".into(),
            ));
        }
        self.make_current()?;
        let n = usize::try_from(bytes).map_err(|_| {
            refused(
                "DisplayGpu::import_store",
                format!("{bytes:#x} does not fit usize"),
            )
        })?;
        let p = self
            .cu
            .import_and_map(self.device, fd, n)
            .map_err(|name| CudaError::Refused {
                what: "cuMemImportFromShareableHandle + cuMemMap (display)",
                code: 0,
                name,
            })?;
        self.store = Some((p, bytes));
        Ok(())
    }

    /// The store address of `[off, off+len)`, refused by name unless wholly inside the store.
    fn at(&self, off: u64, len: usize, what: &'static str) -> Result<CUdeviceptr, CudaError> {
        let Some((base, bytes)) = self.store else {
            return Err(refused(what, "no store imported".into()));
        };
        if off.checked_add(len as u64).is_none_or(|e| e > bytes) {
            return Err(refused(
                what,
                format!("[{off:#x}, +{len:#x}) leaves the {bytes:#x}-byte store"),
            ));
        }
        Ok(base + off)
    }

    /// ★ Read `buf.len()` bytes of the store at `off` — the GPU copies them to host memory (the
    /// display instance memory's context-DMA table, a video-memory semaphore).
    ///
    /// # Errors
    /// Refused by name outside the store; the CUDA error otherwise.
    pub fn read_store(&self, off: u64, buf: &mut [u8]) -> Result<(), CudaError> {
        let src = self.at(off, buf.len(), "DisplayGpu::read_store")?;
        self.cu
            .memcpy_d2h(buf, src, "cuMemcpyDtoH(display read_store)")
    }

    /// ★ Write `bytes` into the store at `off` (a video-memory notifier or semaphore release).
    ///
    /// # Errors
    /// Refused by name outside the store; the CUDA error otherwise.
    pub fn write_store(&self, off: u64, bytes: &[u8]) -> Result<(), CudaError> {
        let dst = self.at(off, bytes.len(), "DisplayGpu::write_store")?;
        self.cu
            .memcpy_h2d(dst, bytes, "cuMemcpyHtoD(display write_store)")
    }

    /// ★ Zero `[off, off+len)` of the store (the guest's display instance memory when it is stated:
    /// the guest never zeroes it, `disp_inst_mem.c:170-201`).
    ///
    /// # Errors
    /// Refused by name outside the store; the CUDA error otherwise.
    pub fn zero_store(&self, off: u64, len: u64) -> Result<(), CudaError> {
        let n = usize::try_from(len)
            .map_err(|_| refused("DisplayGpu::zero_store", format!("{len:#x}")))?;
        let dst = self.at(off, n, "DisplayGpu::zero_store")?;
        self.cu
            .memset_d8(dst, 0, n, "cuMemsetD8(display zero_store)")
    }
}

impl Drop for DisplayGpu {
    fn drop(&mut self) {
        // the stream drains (every queued host signal with it) before the context goes
        self.cu.stream_destroy(self.stream);
        self.cu.event_destroy(self.color_event);
        self.cu.event_destroy(self.signal_event);
        if let Some((p, _)) = self.staging.take() {
            self.cu.mem_free(p);
        }
        // the checksum's page-locked half is the context's, reclaimed with it
        if let Some((p, _, _)) = self.sums.take() {
            self.cu.mem_free(p);
        }
        if let Some((p, _)) = self.color_frame.take() {
            self.cu.mem_free(p);
        }
        if let Some(p) = self.color_luts.take() {
            self.cu.mem_free(p);
        }
        if let Some(p) = self.color_pipelines.take() {
            self.cu.mem_free(p);
        }
        if let Some((p, _)) = self.color_status.take() {
            self.cu.mem_free(p);
        }
        self.cu.ctx_destroy(self.ctx);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn color_ptx_matches_its_source_and_launch_abi() {
        let mut h: u64 = 0xcbf2_9ce4_8422_2325;
        for b in include_bytes!("../../../cuda/display/kf_color.cu") {
            h = (h ^ u64::from(*b)).wrapping_mul(0x0000_0100_0000_01b3);
        }
        let ptx = std::str::from_utf8(COLOR_PTX).unwrap();
        assert!(ptx.is_ascii());
        assert!(ptx.contains(&format!("// source fnv1a64: {h:016x}")));
        let types = |name| {
            ptx.split(&format!(".visible .entry {name}("))
                .nth(1)
                .unwrap()
                .split(')')
                .next()
                .unwrap()
                .split(',')
                .map(|p| {
                    let w: Vec<_> = p.split_whitespace().collect();
                    w[1..w.len() - 1].join(" ")
                })
                .collect::<Vec<_>>()
        };
        // clang spells signed C ints as .u32; all are passed as four-byte bit patterns.
        let mut compose = vec![".u64 .ptr .align 1", ".u64 .ptr .align 1"];
        compose.extend([".u32"; 15]);
        compose.extend([".u64 .ptr .align 1", ".u32", ".u32"]);
        compose.extend([
            ".u64 .ptr .align 1",
            ".u32",
            ".u32",
            ".u64 .ptr .align 1",
            ".u64 .ptr .align 1",
        ]);
        assert_eq!(types("kf_color_compose"), compose);
        assert_eq!(
            types("kf_tmo_validate"),
            [".u64 .ptr .align 1", ".u32", ".u64 .ptr .align 1"]
        );
        assert_eq!(
            types("kf_color_validate"),
            [".u64 .ptr .align 1", ".u32", ".u64 .ptr .align 1"]
        );
        assert_eq!(
            types("kf_color_output"),
            [
                ".u64 .ptr .align 1",
                ".u64 .ptr .align 1",
                ".u32",
                ".u64 .ptr .align 1",
                ".u32",
                ".align 4 .b8",
                ".u32"
            ]
        );
        assert!(
            ptx.contains("kf_color_output_param_5[48]"),
            "twelve encoded matrix coefficients"
        );
    }

    /// ⊘ The compose launch passes EIGHTEEN by-value parameters (two u64, twelve u32, four s32) in
    /// this order; the PTX entry must declare exactly those — a drift is a wild pointer on the GPU.
    #[test]
    fn the_compose_kernel_declares_the_parameters_the_launch_passes() {
        let ptx = std::str::from_utf8(SCANOUT_PTX).unwrap();
        assert!(
            ptx.is_ascii(),
            "the PTX parser refuses other bytes, even in comments"
        );
        let head = ptx
            .split(&format!(".visible .entry {COMPOSE_ENTRY}("))
            .nth(1)
            .expect("the entry");
        let params: Vec<(&str, &str)> = head
            .split(')')
            .next()
            .unwrap()
            .split(',')
            .map(|p| {
                let w: Vec<&str> = p.split_whitespace().collect();
                (w[1], w[2].rsplit('_').next().unwrap())
            })
            .collect();
        let want = [
            (".u64", "src"),
            (".u64", "dst"),
            (".u32", "layout"),
            (".u32", "pitch"),
            (".u32", "bh"),
            (".u32", "x0b"),
            (".u32", "y0"),
            (".u32", "width"),
            (".u32", "ox"),
            (".u32", "oy"),
            (".u32", "dpitch"),
            (".u32", "fw"),
            (".u32", "fh"),
            (".u32", "flags"),
            (".s32", "as"),
            (".s32", "bs"),
            (".s32", "ad"),
            (".s32", "bd"),
        ];
        assert_eq!(params, want);
        assert!(
            ptx.contains(".target sm_75"),
            "Turing+ JIT target (sec. 21)"
        );
    }

    /// ⊘ The checksum launch passes FOUR by-value parameters (two u64 pointers, two u32) in this
    /// order; the PTX entry must declare exactly those, in a module of its own.
    #[test]
    fn the_sum_kernel_declares_the_parameters_the_launch_passes() {
        let ptx = std::str::from_utf8(SUM_PTX).unwrap();
        assert!(ptx.is_ascii(), "the PTX parser refuses other bytes");
        assert!(ptx.contains(".target sm_75") && ptx.contains(".version 6.4"));
        let head = ptx
            .split(&format!(".visible .entry {SUM_ENTRY}("))
            .nth(1)
            .expect("the entry");
        let params: Vec<(&str, &str)> = head
            .split(')')
            .next()
            .unwrap()
            .split(',')
            .map(|p| {
                let w: Vec<&str> = p.split_whitespace().collect();
                (w[1], w[2].rsplit('_').next().unwrap())
            })
            .collect();
        assert_eq!(
            params,
            [
                (".u64", "src"),
                (".u64", "out"),
                (".u32", "width"),
                (".u32", "pitch")
            ]
        );
        let scan = std::str::from_utf8(SCANOUT_PTX).unwrap();
        assert!(
            !scan.contains(SUM_ENTRY),
            "kf_sum is not in the compose module"
        );
    }

    /// ⊘ The pack launch passes TWELVE by-value parameters (two u64 pointers, four u32, one u64,
    /// five u32) in this order; the generated PTX entry must declare exactly those.
    #[test]
    fn the_pack_kernel_declares_the_parameters_the_launch_passes() {
        let ptx = std::str::from_utf8(PACK_PTX).unwrap();
        assert!(ptx.is_ascii(), "the PTX parser refuses other bytes");
        assert!(ptx.contains(".target sm_75"));
        let head = ptx
            .split(&format!(".visible .entry {PACK_ENTRY}("))
            .nth(1)
            .expect("the entry");
        let types: Vec<String> = head
            .split(')')
            .next()
            .unwrap()
            .split(',')
            .map(|p| {
                let w: Vec<&str> = p.split_whitespace().collect();
                // `.param .u64 .ptr .align 1 name` or `.param .u32 name`
                w[1..w.len() - 1].join(" ")
            })
            .collect();
        let want = [
            ".u64 .ptr .align 1",
            ".u64 .ptr .align 1",
            ".u32",
            ".u32",
            ".u32",
            ".u32",
            ".u64",
            ".u32",
            ".u32",
            ".u32",
            ".u32",
            ".u32",
        ];
        assert_eq!(types, want);
    }

    /// ★ The committed PTX was generated from the committed source: its header's FNV-1a 64 of
    /// `kf_bl_pack.cu` is the source's (a `.cu` edited without `make_pack_ptx.sh` turns red here,
    /// with no clang needed).
    #[test]
    fn the_pack_ptx_was_made_from_the_committed_source() {
        let src = include_bytes!("../../../cuda/display/kf_bl_pack.cu");
        let mut h: u64 = 0xcbf2_9ce4_8422_2325;
        for b in src {
            h ^= u64::from(*b);
            h = h.wrapping_mul(0x0000_0100_0000_01b3);
        }
        let ptx = std::str::from_utf8(PACK_PTX).unwrap();
        let stated = ptx
            .lines()
            .find_map(|l| l.strip_prefix("// source fnv1a64: "))
            .expect("the header names its source");
        assert_eq!(
            stated.trim(),
            format!("{h:016x}"),
            "re-run cuda/display/make_pack_ptx.sh"
        );
    }

    /// ★ The committed YUV PTX was generated from the committed source (re-run
    /// `cuda/display/make_yuv_ptx.sh`), declares the parameters the launch passes (3 pointers and 17
    /// u32), and is ASCII.
    #[test]
    fn the_yuv_ptx_was_made_from_the_committed_source_and_matches_its_launch() {
        let src = include_bytes!("../../../cuda/display/kf_yuv.cu");
        let mut h: u64 = 0xcbf2_9ce4_8422_2325;
        for b in src {
            h ^= u64::from(*b);
            h = h.wrapping_mul(0x0000_0100_0000_01b3);
        }
        let ptx = std::str::from_utf8(YUV_PTX).unwrap();
        assert!(ptx.is_ascii(), "the PTX parser refuses other bytes");
        let stated = ptx
            .lines()
            .find_map(|l| l.strip_prefix("// source fnv1a64: "))
            .expect("the header names its source");
        assert_eq!(stated.trim(), format!("{h:016x}"), "re-run make_yuv_ptx.sh");
        for entry in [YUV_ENTRY, YUV_COLOR_ENTRY] {
            let head = ptx
                .split(&format!(".visible .entry {entry}("))
                .nth(1)
                .expect("the entry");
            let params = head.split(')').next().unwrap().split(',').count();
            assert_eq!(params, 20, "{entry}");
            assert_eq!(
                head.split(')')
                    .next()
                    .unwrap()
                    .matches(".param .u64 .ptr")
                    .count(),
                3
            );
        }
    }

    /// The YUV launch is bounded before it is queued, independently of the planner.
    #[test]
    fn a_yuv_launch_is_bounded_before_it_is_queued() {
        let ok = YuvLayer {
            y_src: 0,
            y_extent: 63 * 128 + 64,
            c_src: 0,
            c_extent: 23 * 128 + 64,
            block_linear: false,
            y_pitch: 128,
            c_pitch: 128,
            block_height_log2: 0,
            sx0: 0,
            sy0: 0,
            sw: 64,
            sh: 48,
            ox: 10,
            oy: 10,
            dw: 100,
            dh: 60,
            sub_x_log2: 1,
            sub_y_log2: 1,
            vu_first: true,
        };
        // luma needs (48-1)*128+64, chroma (24-1)*128+64
        let ok = YuvLayer {
            y_extent: 47 * 128 + 64,
            ..ok
        };
        assert_eq!(ok.check(120, 90), Ok(()));
        assert!(ok.check(109, 90).is_err(), "right edge");
        assert!(ok.check(120, 69).is_err(), "bottom edge");
        assert!(
            YuvLayer {
                y_extent: 47 * 128 + 63,
                ..ok
            }
            .check(120, 90)
            .is_err()
        );
        assert!(
            YuvLayer {
                c_extent: 23 * 128 + 63,
                ..ok
            }
            .check(120, 90)
            .is_err()
        );
        assert!(
            YuvLayer { c_pitch: 63, ..ok }.check(120, 90).is_err(),
            "narrow chroma pitch"
        );
        assert!(YuvLayer { sw: 0, ..ok }.check(120, 90).is_err());
        assert!(
            YuvLayer {
                sub_x_log2: 2,
                ..ok
            }
            .check(120, 90)
            .is_err()
        );
        assert!(
            YuvLayer {
                block_linear: true,
                block_height_log2: 6,
                ..ok
            }
            .check(120, 90)
            .is_err()
        );
    }

    /// The pack's host-side bounds: the geometry is re-derived, the layout must be a permutation,
    /// the extent must fit the slot, the staging frame must hold the frame.
    #[test]
    fn a_pack_launch_is_bounded_before_it_is_queued() {
        let hd = BlPack {
            width: 1920,
            height: 1080,
            gobs_per_row: 120,
            h_log2: 4,
            gobs: 9 * 120 * 16,
            bits: [4, 5, 6, 7, 8],
        };
        let slot = 10 << 20;
        let staging = 1920 * 1080 * 4;
        assert_eq!(hd.check(slot, staging), Ok(()));
        assert!(hd.check(8_847_359, staging).is_err(), "one byte short");
        assert!(hd.check(slot, staging - 1).is_err(), "short staging");
        for bad in [
            BlPack {
                gobs_per_row: 121,
                ..hd
            },
            BlPack {
                gobs: hd.gobs + 1,
                ..hd
            },
            BlPack {
                bits: [4, 4, 6, 7, 8],
                ..hd
            },
            BlPack {
                bits: [3, 5, 6, 7, 8],
                ..hd
            },
            BlPack { h_log2: 6, ..hd },
            BlPack { width: 0, ..hd },
        ] {
            assert!(bad.check(slot, staging).is_err(), "{bad:?}");
        }
    }

    /// The host-side bounds of a compose launch: reads in the layer's extent, writes in the frame.
    #[test]
    fn a_compose_launch_is_bounded_before_it_is_queued() {
        let bl = ComposeLayer {
            src: 0,
            extent: 9 * 120 * 16 * 512,
            block_linear: true,
            pitch: 120,
            block_height_log2: 4,
            x0_bytes: 0,
            y0: 0,
            width: 1920,
            rows: 1080,
            ox: 0,
            oy: 0,
            flags: 4,
            a_s: 255,
            b_s: 0,
            a_d: 0,
            b_d: 0,
        };
        assert_eq!(bl.check(1920, 1080), Ok(()));
        assert!(bl.check(1919, 1080).is_err(), "wider than the frame");
        let mut t = bl;
        t.extent -= 1;
        assert!(t.check(1920, 1080).is_err(), "one byte short of the blocks");
        let mut t = bl;
        t.pitch = 119;
        assert!(t.check(1920, 1080).is_err(), "rows wider than the surface");
        let mut t = bl;
        (t.ox, t.width) = (1800, 250);
        assert!(
            t.check(1920, 1080).is_err(),
            "unclipped past the right edge"
        );
        let p = ComposeLayer {
            block_linear: false,
            pitch: 7680,
            extent: 1079 * 7680 + 7680,
            ..bl
        };
        assert_eq!(p.check(1920, 1080), Ok(()));
        let mut t = p;
        t.pitch = 7676;
        assert!(t.check(1920, 1080).is_err(), "a row wider than the pitch");
        // §O: the XOR bit is known; a bit beyond it is refused
        assert_eq!(ComposeLayer { flags: 8, ..p }.check(1920, 1080), Ok(()));
        assert!(
            ComposeLayer { flags: 16, ..p }.check(1920, 1080).is_err(),
            "an unknown flag"
        );
    }
}
