#!/usr/bin/env bash
# ★ DERIVE the display plane's wire layouts by COMPILING ogkm's own headers — no parsing of C.
#
# The display link (`crates/kf-rm/src/display.rs`) answers ~30 physical-RM display controls whose
# params are plain C structs in the SDK (`ctrl0073*.h`, `ctrl5070*.h`, `ctrlc370*.h`, `ctrlc372*.h`,
# `nvos.h`). This script asks the COMPILER for each struct's size and each named member's offset and
# size, and for the value of each named constant, and writes one TSV row per fact:
#     SIZE   <struct>                 <sizeof>
#     FIELD  <struct> <member>        <offsetof> <sizeof member>
#     CONST  <name>                   <value>
# `kf_disp::layout` reads the TSV at compile time (include_str!) and refuses a missing name loudly.
# ⚠ Per driver TAG: today 580.159.04 (the bench). The driver matrix (tools/drivermatrix) is where
# these belong once a second guest version needs display — V3_DISPLAY.md §6 risk 6.
#
# usage: tools/derive_display_layouts.sh [path-to-ogkm] > crates/kf-disp/data/layouts-<version>.tsv
set -euo pipefail
OG=${1:-/workspace/nvidia-gpu-passthrough/research_clones/ogkm-580.159.04}
INC="$OG/src/common/sdk/nvidia/inc"
[ -d "$INC/ctrl/ctrl0073" ] || { echo "⊘ no SDK headers at $INC" >&2; exit 2; }
VER=$(sed -n 's/^NVIDIA_VERSION = //p' "$OG/version.mk")
tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT
# struct:member pairs (member may be a nested path like `data[0].type` or `head[1].headIndex`)
FIELDS=(
  NV2080_CTRL_INTERNAL_DISPLAY_GET_STATIC_INFO_PARAMS:feHwSysCap
  NV2080_CTRL_INTERNAL_DISPLAY_GET_STATIC_INFO_PARAMS:windowPresentMask
  NV2080_CTRL_INTERNAL_DISPLAY_GET_STATIC_INFO_PARAMS:numHeads
  NV2080_CTRL_INTERNAL_DISPLAY_GET_STATIC_INFO_PARAMS:i2cPort
  NV2080_CTRL_INTERNAL_DISPLAY_GET_STATIC_INFO_PARAMS:numDispChannels
  NV2080_CTRL_INTERNAL_DISPLAY_WRITE_INST_MEM_PARAMS:instMemPhysAddr
  NV2080_CTRL_INTERNAL_DISPLAY_WRITE_INST_MEM_PARAMS:instMemSize
  NV2080_CTRL_INTERNAL_DISPLAY_WRITE_INST_MEM_PARAMS:instMemAddrSpace
  NV2080_CTRL_INTERNAL_DISPLAY_CHANNEL_PUSHBUFFER_PARAMS:addressSpace
  NV2080_CTRL_INTERNAL_DISPLAY_CHANNEL_PUSHBUFFER_PARAMS:physicalAddr
  NV2080_CTRL_INTERNAL_DISPLAY_CHANNEL_PUSHBUFFER_PARAMS:limit
  NV2080_CTRL_INTERNAL_DISPLAY_CHANNEL_PUSHBUFFER_PARAMS:cacheSnoop
  NV2080_CTRL_INTERNAL_DISPLAY_CHANNEL_PUSHBUFFER_PARAMS:hclass
  NV2080_CTRL_INTERNAL_DISPLAY_CHANNEL_PUSHBUFFER_PARAMS:channelInstance
  NV2080_CTRL_INTERNAL_DISPLAY_CHANNEL_PUSHBUFFER_PARAMS:valid
  NV2080_CTRL_INTERNAL_DISPLAY_CHANNEL_PUSHBUFFER_PARAMS:pbTargetAperture
  NV2080_CTRL_INTERNAL_DISPLAY_CHANNEL_PUSHBUFFER_PARAMS:channelPBSize
  NV0073_CTRL_SYSTEM_GET_CAPS_V2_PARAMS:capsTbl
  NV0073_CTRL_SYSTEM_GET_NUM_HEADS_PARAMS:numHeads
  NV0073_CTRL_SYSTEM_GET_SUPPORTED_PARAMS:displayMask
  NV0073_CTRL_SYSTEM_GET_SUPPORTED_PARAMS:displayMaskDDC
  NV0073_CTRL_SYSTEM_GET_CONNECT_STATE_PARAMS:flags
  NV0073_CTRL_SYSTEM_GET_CONNECT_STATE_PARAMS:displayMask
  NV0073_CTRL_SYSTEM_GET_CONNECT_STATE_PARAMS:retryTimeMs
  NV0073_CTRL_SYSTEM_GET_ACTIVE_PARAMS:head
  NV0073_CTRL_SYSTEM_GET_ACTIVE_PARAMS:displayId
  NV0073_CTRL_SYSTEM_GET_BOOT_DISPLAYS_PARAMS:bootDisplayMask
  NV0073_CTRL_SYSTEM_GET_HEAD_ROUTING_MAP_PARAMS:displayMask
  NV0073_CTRL_SYSTEM_GET_HEAD_ROUTING_MAP_PARAMS:headRoutingMap
  NV0073_CTRL_SYSTEM_GET_INTERNAL_DISPLAYS_PARAMS:availableInternalDisplaysMask
  NV0073_CTRL_SPECIFIC_GET_ALL_HEAD_MASK_PARAMS:headMask
  NV0073_CTRL_SPECIFIC_GET_VALID_HEAD_WINDOW_ASSIGNMENT_PARAMS:windowHeadMask
  NV0073_CTRL_SPECIFIC_OR_GET_INFO_PARAMS:displayId
  NV0073_CTRL_SPECIFIC_OR_GET_INFO_PARAMS:index
  NV0073_CTRL_SPECIFIC_OR_GET_INFO_PARAMS:type
  NV0073_CTRL_SPECIFIC_OR_GET_INFO_PARAMS:protocol
  NV0073_CTRL_SPECIFIC_OR_GET_INFO_PARAMS:location
  NV0073_CTRL_SPECIFIC_OR_GET_INFO_PARAMS:bIsLitByVbios
  NV0073_CTRL_SPECIFIC_OR_GET_INFO_PARAMS:bIsDispDynamic
  NV0073_CTRL_SPECIFIC_GET_CONNECTOR_DATA_PARAMS:displayId
  NV0073_CTRL_SPECIFIC_GET_CONNECTOR_DATA_PARAMS:flags
  NV0073_CTRL_SPECIFIC_GET_CONNECTOR_DATA_PARAMS:count
  NV0073_CTRL_SPECIFIC_GET_CONNECTOR_DATA_PARAMS:data[0].index
  NV0073_CTRL_SPECIFIC_GET_CONNECTOR_DATA_PARAMS:data[0].type
  NV0073_CTRL_SPECIFIC_GET_CONNECTOR_DATA_PARAMS:data[0].location
  NV0073_CTRL_SPECIFIC_GET_CONNECTOR_DATA_PARAMS:platform
  NV0073_CTRL_SPECIFIC_GET_TYPE_PARAMS:displayId
  NV0073_CTRL_SPECIFIC_GET_TYPE_PARAMS:displayType
  NV0073_CTRL_SPECIFIC_GET_EDID_V2_PARAMS:displayId
  NV0073_CTRL_SPECIFIC_GET_EDID_V2_PARAMS:bufferSize
  NV0073_CTRL_SPECIFIC_GET_EDID_V2_PARAMS:flags
  NV0073_CTRL_SPECIFIC_GET_EDID_V2_PARAMS:edidBuffer
  NV0073_CTRL_SPECIFIC_SET_EDID_V2_PARAMS:displayId
  NV0073_CTRL_SPECIFIC_SET_EDID_V2_PARAMS:bufferSize
  NV0073_CTRL_SPECIFIC_SET_EDID_V2_PARAMS:edidBuffer
  NV0073_CTRL_SPECIFIC_GET_PCLK_LIMIT_PARAMS:displayId
  NV0073_CTRL_SPECIFIC_GET_PCLK_LIMIT_PARAMS:pclkLimit
  NV0073_CTRL_SPECIFIC_GET_PCLK_LIMIT_PARAMS:orPclkLimit
  NV0073_CTRL_SPECIFIC_GET_PCLK_LIMIT_PARAMS:vbPclkLimit
  NV0073_CTRL_SPECIFIC_IS_DIRECTMODE_DISPLAY_PARAMS:bIsDirectmode
  NV0073_CTRL_DFP_GET_INFO_PARAMS:displayId
  NV0073_CTRL_DFP_GET_INFO_PARAMS:flags
  NV0073_CTRL_DFP_GET_INFO_PARAMS:UHBRSupportedByDfp
  NV0073_CTRL_DFP_GET_DISPLAYPORT_DONGLE_INFO_PARAMS:flags
  NV0073_CTRL_DFP_GET_DISPLAYPORT_DONGLE_INFO_PARAMS:maxTmdsClkRateHz
  NV5070_CTRL_SYSTEM_GET_CAPS_V2_PARAMS:capsTbl
  NVC370_CTRL_CMD_GET_CHANNEL_INFO_PARAMS:channelClass
  NVC370_CTRL_CMD_GET_CHANNEL_INFO_PARAMS:channelInstance
  NVC370_CTRL_CMD_GET_CHANNEL_INFO_PARAMS:IsChannelInDebugMode
  NVC370_CTRL_CMD_GET_CHANNEL_INFO_PARAMS:channelState
  NVC370_CTRL_IDLE_CHANNEL_PARAMS:channelClass
  NVC370_CTRL_IDLE_CHANNEL_PARAMS:channelInstance
  NVC370_CTRL_SET_ACCL_PARAMS:channelClass
  NVC370_CTRL_GET_ACCL_PARAMS:channelClass
  NVC370_CTRL_GET_LOCKPINS_CAPS_PARAMS:frameLockPin
  NVC370_CTRL_GET_LOCKPINS_CAPS_PARAMS:rasterLockPin
  NVC370_CTRL_GET_LOCKPINS_CAPS_PARAMS:flipLockPin
  NVC370_CTRL_GET_LOCKPINS_CAPS_PARAMS:stereoPin
  NVC370_CTRL_GET_LOCKPINS_CAPS_PARAMS:numScanLockPins
  NVC370_CTRL_GET_LOCKPINS_CAPS_PARAMS:numFlipLockPins
  NVC370_CTRL_GET_LOCKPINS_CAPS_PARAMS:numStereoPins
  NVC370_CTRL_GET_ACCL_PARAMS:channelInstance
  NVC370_CTRL_GET_ACCL_PARAMS:accelerators
  NVC372_CTRL_IS_MODE_POSSIBLE_PARAMS:bIsPossible
  NVC372_CTRL_IS_MODE_POSSIBLE_PARAMS:minImpVPState
  NVC372_CTRL_IS_MODE_POSSIBLE_PARAMS:minPState
  NVC372_CTRL_IS_MODE_POSSIBLE_PARAMS:minRequiredBandwidthKBPS
  NVC372_CTRL_IS_MODE_POSSIBLE_PARAMS:floorBandwidthKBPS
  NVC372_CTRL_IS_MODE_POSSIBLE_PARAMS:minRequiredHubclkKHz
  NVC372_CTRL_IS_MODE_POSSIBLE_PARAMS:dispClkKHz
  NVC372_CTRL_IS_MODE_POSSIBLE_PARAMS:worstCaseMargin
  NV50VAIO_CHANNELDMA_ALLOCATION_PARAMETERS:channelInstance
  NV50VAIO_CHANNELDMA_ALLOCATION_PARAMETERS:hObjectBuffer
  NV50VAIO_CHANNELDMA_ALLOCATION_PARAMETERS:hObjectNotify
  NV50VAIO_CHANNELDMA_ALLOCATION_PARAMETERS:offset
  NV50VAIO_CHANNELPIO_ALLOCATION_PARAMETERS:channelInstance
)
CONSTS=(
  NV0073_CTRL_SPECIFIC_OR_TYPE_SOR NV0073_CTRL_SPECIFIC_OR_PROTOCOL_SOR_SINGLE_TMDS_A
  NV0073_CTRL_SPECIFIC_OR_LOCATION_CHIP NV0073_CTRL_SPECIFIC_CONNECTOR_DATA_TYPE_DVI_D
  NV0073_CTRL_SPECIFIC_CONNECTOR_PLATFORM_DEFAULT_ADD_IN_CARD NV0073_CTRL_SPECIFIC_DISPLAY_TYPE_DFP
  NV0073_CTRL_SPECIFIC_MAX_WINDOWS NV0073_CTRL_MAX_CONNECTORS NV0073_CTRL_SPECIFIC_GET_EDID_MAX_EDID_BYTES
  NVC370_CTRL_GET_CHANNEL_INFO_STATE_IDLE NVC370_CTRL_GET_CHANNEL_INFO_STATE_BUSY
  NVC370_CTRL_GET_CHANNEL_INFO_STATE_DEALLOC
  NV0073_CTRL_CMD_SYSTEM_GET_CAPS_V2 NV0073_CTRL_CMD_SYSTEM_GET_NUM_HEADS NV0073_CTRL_CMD_SYSTEM_GET_SUPPORTED
  NV0073_CTRL_CMD_SYSTEM_GET_CONNECT_STATE NV0073_CTRL_CMD_SYSTEM_GET_ACTIVE NV0073_CTRL_CMD_SYSTEM_GET_BOOT_DISPLAYS
  NV0073_CTRL_CMD_SYSTEM_GET_HEAD_ROUTING_MAP NV0073_CTRL_CMD_SYSTEM_MAP_SHARED_DATA
  NV0073_CTRL_CMD_SYSTEM_GET_INTERNAL_DISPLAYS NV0073_CTRL_CMD_SPECIFIC_GET_ALL_HEAD_MASK
  NV0073_CTRL_CMD_SPECIFIC_GET_VALID_HEAD_WINDOW_ASSIGNMENT NV0073_CTRL_CMD_SPECIFIC_OR_GET_INFO
  NV0073_CTRL_CMD_SPECIFIC_GET_CONNECTOR_DATA NV0073_CTRL_CMD_SPECIFIC_GET_TYPE NV0073_CTRL_CMD_SPECIFIC_GET_EDID_V2
  NV0073_CTRL_CMD_SPECIFIC_SET_EDID_V2 NV0073_CTRL_CMD_SPECIFIC_GET_PCLK_LIMIT
  NV0073_CTRL_CMD_SPECIFIC_IS_DIRECTMODE_DISPLAY NV0073_CTRL_CMD_SPECIFIC_DISPLAY_CHANGE NV0073_CTRL_CMD_DFP_GET_INFO
  NV0073_CTRL_CMD_DFP_GET_DISPLAYPORT_DONGLE_INFO NV0073_CTRL_CMD_SPECIFIC_GET_BACKLIGHT_BRIGHTNESS
  NV5070_CTRL_CMD_SYSTEM_GET_CAPS_V2 NVC370_CTRL_CMD_IDLE_CHANNEL NVC370_CTRL_CMD_SET_ACCL NVC370_CTRL_CMD_GET_ACCL
  NVC370_CTRL_CMD_GET_CHANNEL_INFO NVC370_CTRL_CMD_GET_LOCKPINS_CAPS NVC370_CTRL_CMD_SET_SWAPRDY_GPIO_WAR
  NVC372_CTRL_CMD_IS_MODE_POSSIBLE NV2080_CTRL_CMD_INTERNAL_DISPLAY_CHANNEL_PUSHBUFFER
  NVC370_CTRL_GET_LOCKPINS_CAPS_FRAME_LOCK_PIN_NONE NVC370_CTRL_GET_LOCKPINS_CAPS_RASTER_LOCK_PIN_NONE
  NVC370_CTRL_GET_LOCKPINS_CAPS_FLIP_LOCK_PIN_NONE NVC370_CTRL_GET_LOCKPINS_CAPS_STEREO_PIN_NONE
  NV0073_CTRL_DFP_FLAGS_SIGNAL_TMDS NV0073_CTRL_DFP_FLAGS_LINK_SINGLE
  NV0073_CTRL_DFP_GET_DISPLAYPORT_DONGLE_INFO_FLAGS_ATTACHED_FALSE
)
{
  echo '#include <stdio.h>'
  echo '#include <stddef.h>'
  echo '#include "nvtypes.h"'
  echo '#include "nvos.h"'
  for h in "$INC"/ctrl/ctrl0073/*.h "$INC"/ctrl/ctrl5070/*.h "$INC"/ctrl/ctrlc370/*.h "$INC"/ctrl/ctrlc372/*.h \
           "$INC"/ctrl/ctrl2080/ctrl2080internal.h; do echo "#include \"$h\""; done
  echo 'int main(void){'
  seen=""
  for f in "${FIELDS[@]}"; do
    s=${f%%:*}; m=${f#*:}
    case " $seen " in *" $s "*) ;; *) echo "  printf(\"SIZE\\t$s\\t%zu\\n\", sizeof($s));"; seen="$seen $s";; esac
    echo "  printf(\"FIELD\\t$s\\t$m\\t%zu\\t%zu\\n\", offsetof($s, $m), sizeof((($s*)0)->$m));"
  done
  for c in "${CONSTS[@]}"; do echo "  printf(\"CONST\\t$c\\t0x%llx\\n\", (unsigned long long)($c));"; done
  echo '  return 0; }'
} > "$tmp/l.c"
gcc -w -I"$INC" -I"$INC/ctrl" -I"$OG/src/common/inc" -o "$tmp/l" "$tmp/l.c" 2>"$tmp/err" || { echo "⊘ layout program did not compile:" >&2; head -20 "$tmp/err" >&2; exit 3; }
echo "# derived by tools/derive_display_layouts.sh from ogkm $VER — do not edit by hand"
echo "VERSION	$VER"
"$tmp/l"
