#!/usr/bin/env python3
"""emit_rust.py — the committed driver-matrix ranges → `kf-abi/src/generated/matrix.rs`.

  emit_rust.py --ranges traces/driver_matrix/ranges.tsv --out crates/kf-abi/src/generated/matrix.rs

Input is `collapse.py ranges --only consumed.txt` output: MEASURED runs, one row per
(item, run of consecutive tags). Output is data only — no logic, no policy:

- `MEASURED`: every ogkm tag the sweep measured, ascending. A driver version outside it is
  UNMEASURED; every lookup refuses it by name (`kf_abi::matrix::Unmeasured`) — there is no
  nearest-neighbour arm, because a release between two measured tags can move a field (580.95.05
  and 580.105.08 each inserted a GspSystemInfo field mid-branch).
- one `StructRuns` per consumed struct: its distinct layouts (only the CONSUMED fields, plus
  `sizeof`) and the tag runs each one covers;
- one `ValueRuns` per consumed constant (RPC numbers, control ids, class ids, VGX version …).

Regenerate after re-sweeping; the diff IS the review. `kf-abi`'s test
`the_generated_matrix_is_the_committed_ranges` fails if this file and the TSV disagree.
"""
import argparse
import collections


def vkey(tag):
    return tuple(int(x) for x in tag.split("."))


def rust_ident(s):
    out = []
    for ch in s:
        out.append(ch.upper() if ch.isalnum() else "_")
    r = "".join(out)
    while "__" in r:
        r = r.replace("__", "_")
    r = r.strip("_")
    if r and r[0].isdigit():
        r = "_" + r
    return r


def ver(tag):
    a, b, c = (tag.split(".") + ["0", "0"])[:3]
    return f"v({int(a)}, {int(b)}, {int(c)})"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ranges", required=True)
    ap.add_argument("--out", required=True)
    a = ap.parse_args()

    tags = None
    rows = []
    with open(a.ranges) as f:
        for line in f:
            if line.startswith("# tags\t"):
                tags = line.rstrip("\n").split("\t", 1)[1].split()
                continue
            if line.startswith("#") or not line.strip():
                continue
            kind, item, f0, f1, val = line.rstrip("\n").split("\t")
            rows.append((kind, item, f0, f1, val))
    if not tags:
        raise SystemExit("ranges file has no '# tags' line")
    tags = sorted(tags, key=vkey)
    idx = {t: i for i, t in enumerate(tags)}

    # struct -> field -> per-tag value (None = absent)
    sfields = collections.OrderedDict()
    values = collections.OrderedDict()
    for (kind, item, f0, f1, val) in rows:
        span = tags[idx[f0]: idx[f1] + 1]
        if kind in ("sizeof", "field"):
            s, _, p = item.partition(".")
            key = "." if kind == "sizeof" else p
            d = sfields.setdefault(s, collections.OrderedDict()).setdefault(key, {})
            for t in span:
                if val == "ABSENT":
                    d[t] = None
                else:
                    offsz, _, el = val.partition("@")
                    o_, s_ = (int(x) for x in offsz.split("+"))
                    d[t] = (o_, s_, int(el) if el else 0)
        elif kind == "value":
            d = values.setdefault(item, {})
            for t in span:
                d[t] = None if val == "ABSENT" else int(val)

    o = []
    o.append("// @generated by tools/drivermatrix/emit_rust.py from traces/driver_matrix/ranges.tsv\n")
    o.append("// — DO NOT EDIT BY HAND. Regenerate: `tools/drivermatrix/regen.sh`.\n")
    o.append("//\n// Every value below was MEASURED by compiling ogkm at each tag (`tools/drivermatrix/dm.py`:\n")
    o.append("// struct layouts from gcc's DWARF, constants from the preprocessor + a compiled printf).\n")
    o.append("#![allow(clippy::unreadable_literal)]\n\n")
    o.append("//! The driver matrix: consumed NVIDIA ABI facts, per measured ogkm tag.\n")
    o.append("//! See `crate::matrix` for the lookup rules and `docs/design/V3_DRIVER_MATRIX.md`.\n\n")
    o.append("use crate::DriverVersion;\n")
    o.append("use crate::matrix::{FieldAt, Layout, Run, StructRuns, ValueRuns};\n\n")
    o.append("const fn v(major: u16, minor: u16, patch: u16) -> DriverVersion {\n")
    o.append("    DriverVersion { major, minor, patch }\n}\n\n")
    o.append("const fn f(path: &'static str, off: u32, size: i32, elem: i32) -> (&'static str, FieldAt) {\n")
    o.append("    (path, FieldAt { off, size, elem })\n}\n\n")
    o.append("const fn r<T>(first: DriverVersion, last: DriverVersion, value: Option<T>) -> Run<T> {\n")
    o.append("    Run { first, last, value }\n}\n\n")
    o.append(f"/// Every ogkm tag the committed sweep measured, ascending ({len(tags)} tags).\n")
    o.append("pub const MEASURED: &[DriverVersion] = &[\n")
    for t in tags:
        o.append(f"    {ver(t)}, // {t}\n")
    o.append("];\n\n")

    # structs
    o.append("// ── structs ─────────────────────────────────────────────────────────────────\n\n")
    names = []
    for s, fields in sfields.items():
        paths = [p for p in fields if p != "."]
        # distinct layouts over tags
        def tup(t):
            size = fields.get(".", {}).get(t)
            if size is None:
                return None
            return (size[1],) + tuple(fields[p].get(t) for p in paths)
        runs = []
        for t in tags:
            v_ = tup(t)
            if runs and runs[-1][2] == v_:
                runs[-1][1] = t
            else:
                runs.append([t, t, v_])
        distinct = []
        for r in runs:
            if r[2] is not None and r[2] not in distinct:
                distinct.append(r[2])
        ident = rust_ident(s)
        names.append((s, ident))
        for k, lay in enumerate(distinct):
            o.append(f"const {ident}_L{k}: Layout = Layout {{\n    size: {lay[0]},\n    fields: &[\n")
            for p, fv in zip(paths, lay[1:]):
                if fv is None:
                    continue
                o.append(f"        f(\"{p}\", {fv[0]}, {fv[1]}, {fv[2]}),\n")
            o.append("    ],\n};\n")
        o.append(f"/// `{s}` — {len(distinct)} distinct consumed layout(s) over {len(runs)} run(s).\n")
        o.append(f"pub const {ident}: StructRuns = StructRuns {{\n    name: \"{s}\",\n    runs: &[\n")
        for (f0, f1, lay) in runs:
            val = "None" if lay is None else f"Some(&{ident}_L{distinct.index(lay)})"
            o.append(f"        r({ver(f0)}, {ver(f1)}, {val}), // {f0} … {f1}\n")
        o.append("    ],\n};\n\n")

    # values
    o.append("// ── values ──────────────────────────────────────────────────────────────────\n\n")
    vnames = []
    for n, per in values.items():
        ident = rust_ident(n)
        vnames.append((n, ident))
        runs = []
        for t in tags:
            v_ = per.get(t)
            if runs and runs[-1][2] == v_:
                runs[-1][1] = t
            else:
                runs.append([t, t, v_])
        o.append(f"/// `{n}`\npub const {ident}: ValueRuns = ValueRuns {{\n    name: \"{n}\",\n    runs: &[\n")
        for (f0, f1, v_) in runs:
            val = "None" if v_ is None else f"Some({v_:#x})"
            o.append(f"        r({ver(f0)}, {ver(f1)}, {val}), // {f0} … {f1}\n")
        o.append("    ],\n};\n\n")

    o.append("/// Every generated struct table, for whole-matrix tests and the gap report.\n")
    o.append("pub const ALL_STRUCTS: &[&StructRuns] = &[\n")
    for (_s, ident) in names:
        o.append(f"    &{ident},\n")
    o.append("];\n\n/// Every generated value table.\n")
    o.append("pub const ALL_VALUES: &[&ValueRuns] = &[\n")
    for (_n, ident) in vnames:
        o.append(f"    &{ident},\n")
    o.append("];\n")
    with open(a.out, "w") as f:
        f.write("".join(o))


if __name__ == "__main__":
    main()
