#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-or-later
"""windows_twins.py -- each driver-matrix Linux tag's Windows twin, READ from the tag's own nvBldVer.h.

`src/common/inc/nvBldVer.h` carries two buildmeister blocks per release: the Unix one
(`#if defined(NV_LINUX) ...`) and the Windows one (`#else /* Windows builds */`), each with
NV_BUILD_BRANCH_VERSION, NV_BUILD_CHANGELIST_NUM and NV_BUILD_NAME. A Windows guest RM reports its
changelist in fn 1 (`guestClNum = NV_BUILD_CHANGELIST_NUM`, src/nvidia/src/kernel/vgpu/rpc.c), so
"this Windows build is that Linux tag's source snapshot" is checkable on the wire: equal changelists.

usage: windows_twins.py [--git OGKM_GIT_DIR] [--tags tools/drivermatrix/tags.txt]
                        --tsv traces/driver_matrix/windows_twins.tsv
                        --rust crates/kf-abi/src/generated/windows_twins.rs

OGKM_GIT_DIR is a clone of NVIDIA/open-gpu-kernel-modules (a sparse clone is enough: only
`git show <tag>:src/common/inc/nvBldVer.h` is read); a tag it lacks is read from NVIDIA's GitHub
repository at that tag. Nothing is typed by hand: a tag
whose header does not parse is an error, never a guessed row.
"""

import argparse
import re
import subprocess
import sys

UNIX = re.compile(r"#if defined\(NV_LINUX\)[^\n]*\n(.*?)#else\s*/\*\s*Windows builds\s*\*/\n(.*?)#endif", re.S)


def field(block, name):
    m = re.search(rf"#define\s+{name}\s+(\(?\s*\"?[^\n\")]*\"?\s*\)?)", block)
    if not m:
        raise ValueError(f"no {name}")
    return m.group(1).strip().strip("()").strip().strip('"')


RAW = "https://raw.githubusercontent.com/NVIDIA/open-gpu-kernel-modules/{tag}/src/common/inc/nvBldVer.h"


def header(git, tag):
    """The tag's nvBldVer.h: from the local clone, else from NVIDIA's repository at that tag."""
    if git:
        r = subprocess.run(["git", "-C", git, "show", f"{tag}:src/common/inc/nvBldVer.h"],
                           capture_output=True, text=True)
        if r.returncode == 0:
            return r.stdout, "git"
    import urllib.request
    with urllib.request.urlopen(RAW.format(tag=tag), timeout=60) as resp:
        return resp.read().decode(), "github"


def read(git, tag):
    src, how = header(git, tag)
    print(f"  {tag}: nvBldVer.h from {how}", file=sys.stderr)
    m = UNIX.search(src)
    if not m:
        raise ValueError(f"{tag}: no Unix/Windows buildmeister blocks in nvBldVer.h")
    u, w = m.group(1), m.group(2)
    return {
        "linux_tag": tag,
        "linux_cl": int(field(u, "NV_BUILD_CHANGELIST_NUM")),
        "linux_branch": field(u, "NV_BUILD_BRANCH_VERSION"),
        "win_name": field(w, "NV_BUILD_NAME"),
        "win_cl": int(field(w, "NV_BUILD_CHANGELIST_NUM")),
        "win_branch": field(w, "NV_BUILD_BRANCH_VERSION"),
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--git", default="", help="a local ogkm clone (tags missing there are fetched)")
    ap.add_argument("--tags", default="tools/drivermatrix/tags.txt")
    ap.add_argument("--tsv", required=True)
    ap.add_argument("--rust", required=True)
    a = ap.parse_args()
    tags = [t.strip() for t in open(a.tags) if t.strip() and not t.startswith("#")]
    rows = [read(a.git, t) for t in tags]
    cols = ["linux_tag", "linux_cl", "linux_branch", "win_name", "win_cl", "win_branch"]
    with open(a.tsv, "w") as o:
        o.write("# derived by tools/drivermatrix/windows_twins.py from each tag's src/common/inc/nvBldVer.h"
                " -- do not edit by hand\n")
        o.write("\t".join(cols) + "\tsame_cl\n")
        for r in rows:
            o.write("\t".join(str(r[c]) for c in cols) + f"\t{'yes' if r['linux_cl'] == r['win_cl'] else 'no'}\n")
    with open(a.rust, "w") as o:
        o.write("// SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-or-later\n")
        o.write("// @generated by tools/drivermatrix/windows_twins.py from each driver-matrix tag's\n")
        o.write("// src/common/inc/nvBldVer.h (its Unix and Windows buildmeister blocks). Do not edit.\n")
        o.write("//! Each driver-matrix Linux tag's Windows build, as that tag's own `nvBldVer.h` states it.\n\n")
        o.write("/// One driver-matrix tag's two buildmeister blocks.\n")
        o.write("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n")
        o.write("pub struct WindowsTwin {\n")
        o.write("    /// The Linux tag (`tools/drivermatrix/tags.txt`).\n    pub linux_tag: &'static str,\n")
        o.write("    /// The Unix block's `NV_BUILD_CHANGELIST_NUM`.\n    pub linux_cl: u32,\n")
        o.write("    /// The Unix block's `NV_BUILD_BRANCH_VERSION`.\n    pub linux_branch: &'static str,\n")
        o.write("    /// The Windows block's `NV_BUILD_NAME` (the Windows driver version).\n    pub win_name: &'static str,\n")
        o.write("    /// The Windows block's `NV_BUILD_CHANGELIST_NUM`.\n    pub win_cl: u32,\n")
        o.write("    /// The Windows block's `NV_BUILD_BRANCH_VERSION`.\n    pub win_branch: &'static str,\n")
        o.write("}\n\n")
        o.write("/// Every driver-matrix tag, in `tags.txt` order.\n")
        o.write("pub static WINDOWS_TWINS: &[WindowsTwin] = &[\n")
        for r in rows:
            o.write("    WindowsTwin {\n")
            o.write(f"        linux_tag: \"{r['linux_tag']}\",\n        linux_cl: {r['linux_cl']},\n")
            o.write(f"        linux_branch: \"{r['linux_branch']}\",\n        win_name: \"{r['win_name']}\",\n")
            o.write(f"        win_cl: {r['win_cl']},\n        win_branch: \"{r['win_branch']}\",\n")
            o.write("    },\n")
        o.write("];\n")
    # The committed file is rustfmt-clean (CI checks formatting), so format what was emitted.
    subprocess.run(["rustfmt", "--edition", "2024", a.rust], check=True)
    same = sum(r["linux_cl"] == r["win_cl"] for r in rows)
    print(f"windows_twins: {len(rows)} tags, {same} with the same changelist on both builds")


if __name__ == "__main__":
    sys.exit(main())
