#!/usr/bin/env python3
"""Generate the one diagnostic evidence cell from trusted source and pinned retail PE.

No retail code is executed. The registration row RVA is an exact-file research fact,
not a GPU register address or a device-specific constant. Unknown files fail closed.
"""
import argparse
import hashlib
from pathlib import Path
import struct
import subprocess
import tempfile

SHA = "31c79cce80b573e21647ace8d1a2b65697f992e7f86196f89e30af477b1bd47c"
TAG_COMMIT = "307159f2623d3bf45feb9177bd2da52ffbc5ddf9"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ogkm", type=Path, required=True)
    parser.add_argument("--driver", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    commit = subprocess.check_output(["git", "-C", str(args.ogkm), "rev-parse", "HEAD"], text=True).strip()
    if commit != TAG_COMMIT:
        raise SystemExit("requires the exact public OGKM 580.65.06 checkout")
    data = args.driver.read_bytes()
    if hashlib.sha256(data).hexdigest() != SHA:
        raise SystemExit("retail driver digest is not an evidenced cell")
    pe = struct.unpack_from("<I", data, 0x3c)[0]
    if data[pe:pe+4] != b"PE\0\0":
        raise SystemExit("not PE")
    sections, optional = struct.unpack_from("<H", data, pe+6)[0], struct.unpack_from("<H", data, pe+20)[0]
    table = pe + 24 + optional
    def read_rva(rva, size):
        for i in range(sections):
            at = table + 40*i
            va, rawsize, rawoff = struct.unpack_from("<III", data, at+12)
            if va <= rva and rva+size <= va+rawsize:
                return data[rawoff+rva-va:rawoff+rva-va+size]
        raise SystemExit("registration RVA outside raw section")
    # RS_RESOURCE_DESC: the exact-file row independently inspected in b297-usage.md.
    row = read_rva(0x1135a40, 56)
    # Retain the raw row digest as a reproducible audit identity; class is read from it.
    external = struct.unpack_from("<I", row, 0)[0]
    if external != 0xb297:
        raise SystemExit("registration no longer names the inspected class")
    internal, param_size = struct.unpack_from("<I", row, 4)[0], struct.unpack_from("<I", row, 16)[0]
    if internal != 0xf4b771 or param_size != 12:
        raise SystemExit("registration class/layout mismatch")
    image_base = struct.unpack_from("<Q", data, pe+24+24)[0]
    parent_rva = struct.unpack_from("<Q", row, 24)[0] - image_base
    if struct.unpack("<II", read_rva(parent_rva, 8)) != (0x4b01b3, 0):
        raise SystemExit("registration is not Subdevice-only")
    subprocess.run(["git", "-C", str(args.ogkm), "diff", "--exit-code", "HEAD", "--",
                    "src/common/sdk/nvidia/inc"], check=True, stdout=subprocess.DEVNULL)
    with tempfile.TemporaryDirectory(prefix="kf-runlist-layout-") as tmp:
        exe = Path(tmp)/"layout"
        subprocess.run(["cc", "-std=c11", "-Werror", "-I"+str(args.ogkm/"src/common/sdk/nvidia/inc"),
                        str(Path(__file__).with_name("layout.c")), "-o", str(exe)], check=True)
        size, engine, max_tsgs, qos = map(int, subprocess.check_output([str(exe)], text=True).split())
    if size != param_size:
        raise SystemExit("compiled source and retail parameter sizes disagree")
    args.out.write_text(f'''// @generated by tools/windows-runlist-probe/derive.py; do not edit.
// Public source: OGKM 580.65.06 {commit}.
// Retail PE SHA256: {SHA}.
// RS_RESOURCE_DESC RVA 0x1135a40 SHA256: {hashlib.sha256(row).hexdigest()}.
// Diagnostic class evidence only; this is NOT an OGKM-defined class identifier.
pub(super) const CELLS: &[super::EvidenceCell] = &[super::EvidenceCell {{
    wire_version: crate::DriverVersion {{ major: 580, minor: 65, patch: 6 }},
    windows_name: "580.88",
    class: {external:#x},
    size: {size},
    engine: {engine},
    max_tsgs: {max_tsgs},
    qos: {qos},
}}];
''')
    subprocess.run(["rustfmt", "--edition", "2024", str(args.out)], check=True)


if __name__ == "__main__":
    main()
